Repository target/goalert, pull requests merged in 2023-08, with the labels that each got.

#3205 dev: run clean before building in Dockerfile
  devtools/ci/dockerfiles/goalert/Dockerfile
Labels: size/xs

#3225 dev: set email domain to localhost in dev
  Procfile
Labels: size/xs

#3226 deps: update to Go 1.21.0
  devtools/ci/dockerfiles/goalert/Dockerfile
  devtools/ci/tasks/build-all.yml
  devtools/ci/tasks/build-binaries.yml
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/ci/tasks/test-smoketest.yml
  go.mod
  go.sum
Labels: size/xs

#3207 ui: update draggable list ux
  package.json
  web/src/app/escalation-policies/PolicyStep.tsx
  web/src/app/escalation-policies/PolicyStepsCard.js
  web/src/app/escalation-policies/PolicyStepsQuery.tsx
  web/src/app/escalation-policies/stepUtil.tsx
  web/src/app/lists/DraggableListItem.tsx
  web/src/app/lists/FlatList.tsx
  web/src/app/lists/FlatListItem.tsx
  web/src/app/rotations/RotationUserList.tsx
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
  web/src/cypress/e2e/rotations.cy.ts
  yarn.lock
Labels: size/xl

#3233 ui/components: Convert toolBarAction to ts
  web/src/app/main/components/ToolbarAction.tsx
Labels: size/s

#3241 dev: use pgdump-lite for schema generation
  .github/workflows/labeler.yml
  Makefile
  devtools/pgdump-lite/cmd/pgdump-lite/main.go
  devtools/pgdump-lite/dumpschema.go
  devtools/pgdump-lite/pgd/db.go
  devtools/pgdump-lite/pgd/models.go
  devtools/pgdump-lite/pgd/queries.sql.go
  devtools/pgdump-lite/queries.sql
  gadb/models.go
  migrate/schema.sql
  sqlc.yaml
Labels: size/xl

#3246 swo: add guide and in-app documentation
  docs/getting-started.md
  docs/switchover.md
  web/src/app/admin/switchover/AdminSwitchover.tsx
  web/src/app/admin/switchover/AdminSwitchoverGuide.tsx
  web/src/app/main/AppRoutes.tsx
  web/src/app/util/AppLink.tsx
Labels: size/m

#3247 swo: Polish the guide/documentation rendering
  web/src/app/admin/switchover/AdminSWOStatusCard.tsx
  web/src/app/admin/switchover/AdminSwitchover.tsx
  web/src/app/admin/switchover/AdminSwitchoverGuide.tsx
  web/src/app/admin/switchover/SWONode.tsx
Labels: size/s

#3234 fix: prefix search
  escalation/search.go
  notification/search.go
  schedule/rotation/search.go
  schedule/search.go
  search/render.go
  service/search.go
  user/search.go
Labels: size/s

#3253 ui/deps: upgrade mui packages to latest
  package.json
  web/src/app/schedules/calendar/ScheduleCalendarEventWrapper.tsx
  yarn.lock
Labels: size/s

#3251 smtpsrv: return proper errors and limit RCPT TO
  app/cmd.go
  app/config.go
  app/defaults.go
  app/initsmtpsrv.go
  docs/getting-started.md
  smtpsrv/config.go
  smtpsrv/server.go
  smtpsrv/server_test.go
  smtpsrv/session.go
  smtpsrv/session_test.go
Labels: size/l

#3255 dev: update all devtools to use pgx v5
  devtools/fetchcounts/run.go
  devtools/pgdump-lite/cmd/pgdump-lite/main.go
  devtools/pgdump-lite/dumpdata.go
  devtools/pgdump-lite/dumpschema.go
  devtools/pgdump-lite/pgd/db.go
  devtools/pgdump-lite/pgd/queries.sql.go
  devtools/pgmocktime/mocker.go
  devtools/resetdb/main.go
  devtools/waitfor/main.go
  devtools/waitfor/schemapostgres.go
  go.mod
  go.sum
  sqlc.yaml
  test/smoke/harness/harness.go
  util/sqlutil/rollback.go
Labels: size/s

#3242 ui/components: Convert NewUserSetUp to ts
  web/src/app/main/components/NewUserSetup.tsx
  web/src/app/util/RequireConfig.tsx
Labels: size/xs
