Repository target/goalert, pull requests merged in 2023-05, with the labels that each got.

#2977 ui: fix slack link typography in dialog
  web/src/app/main/components/AuthLink.tsx
Labels: size/s

#2932 ui: add slack user groups to on call notifications
  .github/workflows/main.yml
  Makefile
  notification/slack/usergrouperror.go
  notification/slack/usergroupsender.go
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
  web/src/app/schedules/on-call-notifications/hooks.ts
  web/src/app/schedules/on-call-notifications/util.ts
  web/src/app/selection/SlackUserGroupSelect.tsx
  web/src/app/selection/index.js
Labels: size/l

#2990 auth/basic: separate password hashing from DB insert
  app/cmd.go
  auth/basic/db.go
  graphql2/graphqlapp/user.go
Labels: size/s

#3002 dev: switch to wait for page vs time
  test/integration/schedules.spec.ts
  test/integration/timepickers.spec.ts
Labels: size/s

#3025 Fix smtp default port
  config/config.go
  graphql2/mapconfig.go
  notification/email/sender.go
Labels: size/xs

#3028 slack: lower slack cache time
  notification/slack/channel.go
  notification/slack/usergroup.go
Labels: size/s

#3037 slack: use usergroup handle instead of name
  graphql2/graphqlapp/mutation.go
  graphql2/graphqlapp/slack.go
  notification/slack/usergroup.go
  web/src/app/selection/SlackUserGroupSelect.tsx
Labels: size/s

#3038 logs: don't log context canceled errors (e.g., closed browser tab)
  graphql2/graphqlapp/app.go
Labels: size/xs

#3043 ui: convert ScheduleRuleEditDialog to hooks
  web/src/app/schedules/ScheduleRuleEditDialog.js
Labels: size/m

#3048 feat: add table of cli flags to getting started guide
  app/cmd.go
  docs/getting-started.md
Labels: size/s

#3040 fix: webhook check on edit escalation policy step
  graphql2/graphqlapp/escalationpolicy.go
Labels: size/xs
