Repository target/goalert, pull requests merged in 2023-07, with the labels that each got.

#3109 auth/authlink: use sqlc for queries
  auth/authlink/queries.sql
  auth/authlink/store.go
  gadb/queries.sql.go
  sqlc.yaml
Labels: size/s

#3137 feat: add happy path smoke test for slack user groups
  devtools/mockslack/api.go
  devtools/mockslack/server.go
  devtools/mockslack/usergroupsusersupdate.go
  test/smoke/harness/harness.go
  test/smoke/harness/slack.go
  test/smoke/slackusergroup_test.go
Labels: size/m

#3144 chore: remove slack usergroup exp flag
  app/initslack.go
  expflag/flags.go
  graphql2/graphqlapp/mutation.go
  graphql2/graphqlapp/slack.go
  test/smoke/slackusergroup_test.go
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/cypress/e2e/schedules.cy.ts
  web/src/expflag.d.ts
Labels: size/m

#3138 feat: show disabled notification options
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/selection/DisableableMenuItem.tsx
  web/src/app/users/UserContactMethodForm.tsx
Labels: size/m

#3155 feat: add happy path integration test for on call notification webhook
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/s

#3158 auth: use samesite=lax for oauth cookies
  auth/cookies.go
  auth/github/identityprovider.go
  auth/handler.go
  auth/oidc/identityprovider.go
Labels: size/s

#3133 add option to set noise reasons for an alert
  alert/feedback.go
  alert/queries.sql
  alert/store.go
  gadb/models.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/alert.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  migrate/migrations/20230616110941-add-alerts-feedback.sql
  migrate/schema.sql
  web/src/app/alerts/components/AlertDetails.tsx
  web/src/app/alerts/components/AlertFeedback.tsx
  web/src/app/alerts/pages/AlertDetailPage.tsx
  web/src/app/details/CardActions.tsx
  web/src/app/loading/components/LoadingButton.tsx
  web/src/app/services/ServiceNotices.tsx
  web/src/cypress/e2e/alerts.cy.ts
  web/src/schema.d.ts
Labels: size/xl

#3162 feat: add smoke test for on call notification webhooks
  test/smoke/webhook_test.go
  test/smoke/webhookoncall_test.go
Labels: size/s

#3168 feat: remove webhook exp flag
  app/startup.go
  escalation/store.go
  expflag/flags.go
  graphql2/graphqlapp/mutation.go
  test/smoke/webhookoncall_test.go
  web/src/app/escalation-policies/PolicyStepForm.js
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
  web/src/expflag.d.ts
Labels: size/m

#3179 ui/styles: Convert index file to Typescript
  web/src/app/styles/index.tsx
Labels: size/xs

#3156 dev: wait for goalert to start before grpc tool
  Procfile
Labels: size/xs

#3088 heartbeats: Increase max duration and improve UI for long-durations
  heartbeat/monitor.go
  test/integration/service.spec.ts
  web/src/app/services/HeartbeatMonitorForm.tsx
  web/src/app/services/HeartbeatMonitorList.tsx
  web/src/app/util/DurationField.tsx
Labels: size/m

#3167 add API for listing supported integration key types
  graphql2/generated.go
  graphql2/graphqlapp/config.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  test/integration/service.spec.ts
  web/src/app/services/IntegrationKeyForm.tsx
  web/src/app/services/IntegrationKeyList.tsx
  web/src/app/util/RequireConfig.tsx
  web/src/cypress/e2e/services.cy.ts
  web/src/schema.d.ts
Labels: size/m

#3181 alert/alertlog: migrate insert queries to use sqlc
  alert/alertlog/entry.go
  alert/alertlog/queries.sql
  alert/alertlog/store.go
  gadb/db.go
  gadb/models.go
  gadb/queries.sql.go
  go.mod
  go.sum
  sqlc.version
  sqlc.yaml
  swo/swodb/db.go
  swo/swodb/models.go
  swo/swodb/queries.sql.go
Labels: size/l

#3187 alert/alertlog: move remaining problematic queries to sqlc
  Makefile
  alert/alertlog/queries.sql
  alert/alertlog/store.go
  gadb/queries.sql.go
Labels: size/s

#3198 fix: aligning esc policy notices
  web/src/app/details/DetailsPage.tsx
Labels: size/xs

#3199 feat: add service name/id field to webhook alerts
  engine/sendmessage.go
  notification/alert.go
  notification/webhook/sender.go
  test/smoke/webhook_test.go
Labels: size/s

#3182 alert details: show sent notification delivery delays in alert log
  graphql2/graphqlapp/alert.go
  notification/status.go
  notification/store.go
  test/smoke/alertlog_test.go
  test/smoke/alertlogdelay_test.go
Labels: size/m
