Repository target/goalert, pull requests merged in 2023-10, with the labels that each got.

#3331 ui: add ExpFlag component for conditional rendering
  web/src/app/util/useExpFlag.ts
Labels: size/s

#3299 chore: update cypress and graphiql
  .yarnrc.yml
  Makefile
  Makefile.binaries.mk
  cypress.config.js
  devtools/ci/dockerfiles/cypress-env/Dockerfile
  devtools/ci/tasks/test-integration.yml
  devtools/genmake/template.mk
  package.json
  web/src/cypress/e2e/auth.cy.ts
  web/src/cypress/support/navigate-to-and-from.ts
  web/src/esbuild.cypress.js
  web/src/webpack.cypress.js
  yarn.lock
Labels: size/s

#3317 override: use static query for override search
  gadb/queries.sql.go
  graphql2/graphqlapp/useroverride.go
  override/queries.sql
  override/search.go
  sqlc.yaml
  validation/validate/uuid.go
Labels: size/m

#3341 services: update query to return maintenance_expires_at
  service/search.go
Labels: size/xs

#3342 validate/phone: switch to up-to-date phone number library
  devtools/mocktwilio/lookup.go
  go.mod
  go.sum
  graphql2/graphqlapp/toolbox.go
  notification/twilio/sms.go
  notification/twilio/voice.go
  test/smoke/harness/datagen.go
  validation/validate/phone.go
Labels: size/s

#3289 Feature: Full Schedule Support in Calendar Subscriptions
  calsub/http.go
  calsub/queries.sql
  calsub/renderdata.go
  calsub/renderical.go
  calsub/subscriptionconfig.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/calendarsubscription.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeCreateDialog.js
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeEditDialog.js
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeForm.js
  web/src/schema.d.ts
Labels: size/m

#3316 signals: graphql prototype
  app/initgraphql.go
  app/inithttp.go
  app/initstores.go
  dataloader/loader.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/dataloaders.go
  graphql2/graphqlapp/service.go
  graphql2/graphqlapp/servicerule.go
  graphql2/graphqlapp/signal.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  integrationkey/queries.sql
  integrationkey/store.go
  migrate/schema.sql
  service/rule/queries.sql
  service/rule/store.go
  signal/queries.sql
  signal/search.go
  signal/signal.go
  signal/store.go
  signalapi/config.go
  signalapi/notify.go
  signalapi/rule.go
  validation/validate/uuid.go
  web/src/schema.d.ts
Labels: size/xl

#3344 ui/markdown: preserve line breaks in markdown
  package.json
  web/src/app/util/Markdown.js
  yarn.lock
Labels: size/xs

#3355 overrides: fix wrong param in search
  gadb/queries.sql.go
  override/queries.sql
Labels: size/xs

#3257 feat: add monthly rotations UI
  web/src/app/forms/FormField.js
  web/src/app/rotations/HandoffSummary.tsx
  web/src/app/rotations/RotationForm.tsx
  web/src/app/util/timeFormat.test.ts
  web/src/app/util/timeFormat.ts
  web/src/cypress/e2e/rotations.cy.ts
Labels: size/m

#3310 chore: user contactmethod sqlc
  app/initstores.go
  app/inittwilio.go
  dataloader/loader.go
  engine/engine.go
  gadb/queries.sql.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/dataloaders.go
  graphql2/graphqlapp/mutation.go
  graphql2/graphqlapp/user.go
  notification/twilio/carrier.go
  notification/twilio/config.go
  sqlc.yaml
  user/contactmethod/queries.sql
  user/contactmethod/store.go
Labels: size/l

#3345 show alerts to now in graph, update tooltip label
  web/src/app/services/AlertMetrics/AlertCountGraph.tsx
  web/src/app/services/AlertMetrics/AlertMetrics.tsx
  web/src/app/services/AlertMetrics/AlertMetricsFilter.tsx
  web/src/app/services/AlertMetrics/useAlertMetrics.ts
Labels: size/s

#3294 Add Webhook Documentation Links to UI
  web/src/app/documentation/Documentation.tsx
  web/src/app/escalation-policies/PolicyStepForm.js
  web/src/app/users/UserContactMethodForm.tsx
Labels: size/s

#3356 dev: Update Go 1.21.3 and deps
  devtools/ci/dockerfiles/build-env/Dockerfile
  devtools/ci/dockerfiles/goalert/Dockerfile
  devtools/ci/tasks/build-all.yml
  devtools/ci/tasks/build-binaries.yml
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/ci/tasks/test-smoketest.yml
  go.mod
  go.sum
  graphql2/generated.go
Labels: size/xs

#3288 user/favorite: use sqlc for user favorites
  app/initstores.go
  gadb/queries.sql.go
  graphql2/graphqlapp/alert.go
  graphql2/graphqlapp/escalationpolicy.go
  graphql2/graphqlapp/mutation.go
  graphql2/graphqlapp/rotation.go
  graphql2/graphqlapp/schedule.go
  graphql2/graphqlapp/service.go
  graphql2/graphqlapp/user.go
  sqlc.yaml
  user/favorite/queries.sql
  user/favorite/store.go
Labels: size/m

#3300 ui/service-metrics: service metrics hooks
  web/src/app/admin/admin-service-metrics/useServiceMetrics.ts
  web/src/app/admin/admin-service-metrics/useServices.ts
  web/src/app/worker/methods.ts
Labels: size/m

#3359 devtools/resetdb: increase variance in DelayMinutes
  devtools/resetdb/datagen.go
Labels: size/xs

#3361 feat: service rule filter struct translation
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graphqlapp/servicerule.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  service/rule/filter.go
  service/rule/filter_test.go
  service/rule/filterparser.go
  validation/validate/filter.go
  validation/validate/filter_test.go
  web/src/schema.d.ts
Labels: size/xl

#3369 apikey: only enforce unique name on non-deleted keys
  migrate/migrations/20231017112713-api-soft-delete-name.sql
  migrate/schema.sql
Labels: size/s

#3379 fix for missing function
  dataloader/loader.go
Labels: size/xs

#3380 ui: fix default value not set for temp sched dialog
  web/src/app/schedules/ScheduleOverrideList.js
  web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
Labels: size/xs

#3370 apikey: Allow entering a query directly to generate Allowed Fields
  web/src/app/admin/admin-api-keys/AdminAPIKeyForm.tsx
Labels: size/m

#3368 ui/admin: add service metrics data table
  test/integration/admin.spec.ts
  test/integration/lib/service.ts
  test/integration/service.spec.ts
  web/src/app/admin/admin-service-metrics/AdminServiceMetrics.tsx
  web/src/app/admin/admin-service-metrics/AdminServiceTable.tsx
  web/src/app/admin/admin-service-metrics/useServiceMetrics.ts
  web/src/app/admin/admin-service-metrics/useServices.ts
  web/src/app/main/AppRoutes.tsx
  web/src/app/main/NavBar.tsx
Labels: size/xl

#3231 gql: add field "assignedSchedules" to type "User"
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/schedule.go
  graphql2/graphqlapp/user.go
  graphql2/schema.graphql
  oncall/state.go
  oncall/store.go
  schedule/queries.sql
  schedule/store.go
  sqlc.yaml
  user/cache.go
  web/src/schema.d.ts
Labels: size/m
