Repository target/goalert, pull requests merged in 2023-11, with the labels that each got.

#3395 Implement Duplicate Functionality for API Keys
  web/src/app/admin/AdminAPIKeys.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyCreateDialog.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx
Labels: size/m

#3399 create signal UI (POC)
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graphqlapp/servicerule.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  service/rule/rule.go
  service/rule/store.go
  signalapi/notify.go
  web/src/app/main/AppRoutes.tsx
  web/src/app/services/IntegrationKeyList.tsx
  web/src/app/services/ServiceDetails.tsx
  web/src/app/services/ServiceRules/ServiceRuleCreateDialog.tsx
  web/src/app/services/ServiceRules/ServiceRuleDeleteDialog.tsx
  web/src/app/services/ServiceRules/ServiceRuleEditDialog.tsx
  web/src/app/services/ServiceRules/ServiceRuleForm.tsx
  web/src/app/services/ServiceRules/ServiceRulesList.tsx
  web/src/schema.d.ts
Labels: size/xl

#3401 ui/api-keys: add warning icon, update grammar
  web/src/app/admin/AdminAPIKeys.tsx
Labels: size/s

#3400 apikey: Add integration test for GQL API keys
  test/integration/gqlapikeys.spec.ts
  test/integration/lib/flags.ts
  test/integration/setup/scan-flags.ts
  web/src/app/admin/AdminAPIKeys.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyForm.tsx
  web/src/app/main/components/ToolbarPageTitle.tsx
Labels: size/m

#3411 apikey: Switch policy from `allowedFields` to `query`
  apikey/middleware.go
  apikey/policy.go
  apikey/store.go
  graphql2/generated.go
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/gqlapikeys.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  test/integration/gqlapikeys.spec.ts
  web/src/app/admin/AdminAPIKeys.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyCreateDialog.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyEditDialog.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyForm.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyShowQueryDialog.tsx
  web/src/schema.d.ts
Labels: size/l

#3415 apikey: Fix timestamp displays
  web/src/app/admin/AdminAPIKeys.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx
Labels: size/s

#3382 ui/service-metrics: Add filtering for admin service metrics
  web/src/app/admin/admin-service-metrics/AdminServiceFilter.tsx
  web/src/app/admin/admin-service-metrics/AdminServiceMetrics.tsx
  web/src/app/admin/admin-service-metrics/useServiceMetrics.ts
  web/src/app/selection/MaterialSelect.tsx
  web/src/app/selection/QuerySelect.js
Labels: size/l

#3413 users: allow email= in user search
  user/search.go
Labels: size/s

#3414 label: convert non-search store methods to sqlc
  gadb/queries.sql.go
  graphql2/graphqlapp/service.go
  label/queries.sql
  label/store.go
  sqlc.yaml
Labels: size/m

#3427 Go signal to alert logic
  service/rule/store.go
  signalapi/signal.go
Labels: size/m

#3431 ui/urql: update admin queries and mutations
  web/src/app/admin/AdminConfig.tsx
  web/src/app/admin/AdminDialog.tsx
  web/src/app/admin/AdminLimits.tsx
  web/src/app/admin/AdminNumberLookup.tsx
  web/src/app/admin/AdminSMSSend.tsx
  web/src/app/admin/SlackActions.tsx
Labels: size/s

#3432 ui: convert FormContainer to hooks
  web/src/app/forms/FormContainer.js
Labels: size/m

#3297 ui/service-metrics: Add usage graphs
  web/src/app/admin/admin-service-metrics/AdminServiceMetrics.tsx
  web/src/app/admin/admin-service-metrics/AdminServiceTargetGraph.tsx
Labels: size/l

#3453 dev: update Go to 1.21.4 and dependencies
  auth/github/identityprovider.go
  devtools/ci/dockerfiles/goalert/Dockerfile
  devtools/ci/tasks/build-all.yml
  devtools/ci/tasks/build-binaries.yml
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/ci/tasks/test-smoketest.yml
  devtools/runproc/process.go
  go.mod
  go.sum
Labels: dependencies, go, size/xs

#3441 adr: api key architecture
  docs/adrs/000005-api-key-architecture.md
Labels: size/s

#3440 ui: Suspenseful loading
  test/integration/admin.spec.ts
  test/integration/experimental-flags.spec.ts
  web/src/app/actions/auth.js
  web/src/app/admin/AdminAPIKeys.tsx
  web/src/app/admin/AdminNumberLookup.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx
  web/src/app/escalation-policies/PolicyDetails.tsx
  web/src/app/escalation-policies/PolicyStepsCard.js
  web/src/app/index.tsx
  web/src/app/main/App.tsx
  web/src/app/main/RequireAuth.tsx
  web/src/app/main/components/Login.tsx
  web/src/app/rotations/RotationDetails.tsx
  web/src/app/rotations/RotationUserList.tsx
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/ScheduleOverrideList.js
  web/src/app/schedules/ScheduleRuleList.js
  web/src/app/schedules/ScheduleShiftList.tsx
  web/src/app/schedules/calendar/ScheduleCalendar.tsx
  web/src/app/schedules/calendar/ScheduleCalendarEventWrapper.tsx
  web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
  web/src/app/schedules/useScheduleTZ.ts
  web/src/app/selection/QuerySelect.js
  web/src/app/services/HeartbeatMonitorList.tsx
  web/src/app/services/IntegrationKeyList.tsx
  web/src/app/services/ServiceDetails.tsx
  web/src/app/services/ServiceLabelList.tsx
  web/src/app/urql.ts
  web/src/app/users/UserContactMethodList.tsx
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserNotificationRuleList.tsx
  web/src/app/util/RequireConfig.tsx
  web/src/app/util/TelTextField.tsx
  web/src/app/util/useUserInfo.ts
  web/src/cypress/e2e/temporarySchedule.cy.ts
Labels: size/xl

#3433 Go signal to alert
  signalapi/signal.go
Labels: size/s

#3458 dev: fix prettier formatting in vscode
  package.json
  prettier.config.js
  yarn.lock
Labels: size/xs

#3438 ui: convert UserContactMethodSelect to typescript
  web/src/app/users/UserContactMethodSelect.js
  web/src/app/users/UserContactMethodSelect.tsx
Labels: size/m

#3434 apikey: allow copy as JSON and fix query formatting
  web/src/app/admin/admin-api-keys/AdminAPIKeyDrawer.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyShowQueryDialog.tsx
  web/src/app/util/CopyText.tsx
Labels: size/s

#3461 ui/escalation-policies: redirect to details page on create
  web/src/app/escalation-policies/PolicyCreateDialog.tsx
Labels: size/xs

#3455 ui/service-metrics: fix service status in data table
  web/src/app/admin/admin-service-metrics/AdminServiceTable.tsx
Labels: size/xs

#3473 ui/temp-sched: Fix schedule not merging bug
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/temp-sched/TempSchedDialog.tsx
Labels: size/s

#3474 ui/isopicker: Add soft limits for min and max, apply to override and temp sched.
  package.json
  web/src/app/forms/FormContainer.js
  web/src/app/forms/FormField.js
  web/src/app/forms/context.js
  web/src/app/schedules/ScheduleOverrideForm.tsx
  web/src/app/schedules/temp-sched/TempSchedDialog.tsx
  web/src/app/util/ISOPickers.tsx
  yarn.lock
Labels: size/m

#3464 apikey: allow omitting fixed queries
  apikey/middleware.go
Labels: size/xs

#3476 admin/alert-counts: use iso for storage, locale for display
  web/src/app/admin/admin-alert-counts/AlertCountLineGraph.tsx
  web/src/app/admin/admin-alert-counts/useAdminAlertCounts.ts
  web/src/cypress/e2e/admin.cy.ts
Labels: size/m

#3479 ui/message-logs: use a sane limit for the max num of graph points
  web/src/app/admin/admin-message-logs/util.ts
Labels: size/xs

#3478 temp sched dialog: fix soft limits while typing
  web/src/app/schedules/ScheduleOverrideForm.tsx
  web/src/app/schedules/temp-sched/TempSchedDialog.tsx
  web/src/app/util/ISOPickers.tsx
Labels: size/s

#3487 ui: remove unused <Query /> component
  web/src/app/util/Query.js
Labels: size/m

#3229 ui: add user shifts calendar to profile
  web/src/app/loading/components/SpinContainer.tsx
  web/src/app/loading/components/Spinner.tsx
  web/src/app/schedules/ScheduleCalendarQuery.tsx
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserNotificationRuleList.tsx
  web/src/app/users/UserShiftsCalendar.tsx
  web/src/app/util/calendar/Calendar.tsx
  web/src/app/util/calendar/CalendarEventWrapper.tsx
  web/src/app/util/calendar/CalendarToolbar.tsx
  web/src/app/util/calendar/hooks.ts
  web/src/cypress/e2e/scheduleCalendar.cy.ts
  web/src/cypress/e2e/schedules.cy.ts
  web/src/cypress/e2e/temporarySchedule.cy.ts
  web/src/cypress/e2e/timepickers.cy.ts
  web/src/cypress/e2e/users.cy.ts
  web/src/cypress/support/schedule.ts
Labels: size/xl

#3489 ui/urql: rotations
  web/src/app/rotations/RotationAddUserDialog.tsx
  web/src/app/rotations/RotationCreateDialog.tsx
  web/src/app/rotations/RotationForm.tsx
  web/src/app/rotations/RotationFormHandoffTimes.tsx
  web/src/app/util/errutil.ts
Labels: size/l

#3490 ui/profile: convert UserContactMethodVerificationDialog to ts
  web/src/app/users/UserContactMethodVerificationDialog.tsx
Labels: size/s

#3488 ui/profile: convert UserContactMethodCreateDialog to urql
  web/src/app/users/UserContactMethodCreateDialog.tsx
Labels: size/s

#3491 apikey: Fix issue where omitting the `query` field doesn't work
  apikey/middleware.go
  test/integration/gqlapikeys.spec.ts
Labels: size/s

#3495 ui/urql: convert user lists to urql
  web/src/app/users/UserCalendarSubscriptionList.tsx
  web/src/app/users/UserList.tsx
  web/src/app/users/UserOnCallAssignmentList.tsx
  web/src/app/users/UserSessionList.tsx
Labels: size/s
