Repository target/goalert, pull requests merged in 2023-03, with the labels that each got.

#2837 calsub: switch from gorm to sqlc
  .github/workflows/labeler.yml
  Makefile
  calsub/http.go
  calsub/queries.sql
  calsub/store.go
  calsub/subscription.go
  devtools/ci/tasks/scripts/codecheck.sh
  gadb/db.go
  gadb/models.go
  gadb/queries.sql.go
  go.mod
  go.sum
  graphql2/graphqlapp/calendarsubscription.go
  migrate/schema.sql
  sqlc.yaml
Labels: size/l

#2841 readme: add note about overcommit
  docs/getting-started.md
Labels: size/xs

#2842 migrate: add notransaction to ALTER TYPE
  migrate/migrations/20221207150447-webhook-notification-channel-type.sql
  migrate/schema.sql
Labels: size/xs

#2843 ui/deps: update wonka version to latest, fixes yarn.lock generations
  web/src/package.json
  yarn.lock
Labels: size/xs

#2844 dev/make: detect which shasum command to use
  Makefile
  devtools/ci/tasks/scripts/codecheck.sh
Labels: size/xs

#2840 alert: add escalation checks
  alert/logentryfetcher.go
  alert/queries.sql
  alert/store.go
  gadb/queries.sql.go
  sqlc.yaml
  test/smoke/graphqlmultiplealerts_test.go
  test/smoke/harness/harness.go
  test/smoke/missinguser_test.go
  web/src/app/alerts/AlertsList.tsx
  web/src/app/lists/ControlledPaginatedList.tsx
  web/src/cypress/e2e/alerts.cy.ts
Labels: size/m

#2818 Feature/escalate via ivr
  engine/backend.go
  engine/callback.go
  engine/engine.go
  notification/result.go
  notification/result_string.go
  notification/twilio/alertsms.go
  notification/twilio/alertsms_test.go
  notification/twilio/sms.go
  notification/twilio/twiml.go
  notification/twilio/twiml_test.go
  notification/twilio/voice.go
Labels: size/m

#2824 status updates: switch to per-contact-method behavior
  engine/message/db.go
  engine/statusupdatemanager/db.go
  engine/statusupdatemanager/update.go
  gadb/models.go
  graphql2/generated.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  migrate/migrations/20230227124957-cm-status-updates.sql
  migrate/schema.sql
  user/contactmethod/contactmethod.go
  user/contactmethod/store.go
  user/contactmethod/type.go
  web/src/app/users/UserContactMethodEditDialog.js
  web/src/app/users/UserContactMethodForm.tsx
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserStatusUpdatePreference.tsx
  web/src/cypress/e2e/profile.cy.ts
  web/src/esbuild.cypress.js
  web/src/package.json
  web/src/schema.d.ts
  web/src/webpack.cypress.js
Labels: size/l

#2858 chore/go: update dependencies
  go.mod
  go.sum
  notification/slack/channel.go
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
Labels: size/xs

#2863 ui/ISOPickers: Remove fallback code
  web/src/app/util/ISOPickers.tsx
  web/src/cypress/e2e/timepickers.cy.ts
  web/src/cypress/support/form.ts
  web/src/global.d.ts
  web/src/package.json
  yarn.lock
Labels: size/l

#2860 db: switch pending notifications query to use sqlc, remove gorm
  Makefile
  app/app.go
  app/gormjsonlog.go
  app/inithttp.go
  gadb/queries.sql.go
  go.mod
  go.sum
  graphql2/graphqlapp/alert.go
  graphql2/graphqlapp/queries.sql
  sqlc.yaml
  util/sqlutil/context.go
  util/sqlutil/scope.go
Labels: size/m

#2864 slack-dm: fix dm message updates
  notification/slack/channel.go
Labels: size/s

#2855 ui/schedules: Convert ScheduleShiftList to ts
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/ScheduleShiftList.tsx
  web/src/app/schedules/temp-sched/TempSchedAddNewShift.tsx
  web/src/app/schedules/temp-sched/TempSchedDialog.tsx
  web/src/app/schedules/temp-sched/sharedUtils.tsx
  web/src/app/schedules/temp-sched/shiftsListUtil.test.ts
  web/src/app/util/ISOPickers.tsx
Labels: size/s

#2870 deps: Update MUI packages
  test/integration/email-cm.spec.ts
  web/src/app/admin/admin-alert-counts/AlertCountTable.tsx
  web/src/app/alerts/components/AlertsListFilter.tsx
  web/src/app/index.tsx
  web/src/app/main/App.tsx
  web/src/app/mui-pickers.js
  web/src/app/services/AlertMetrics/AlertMetricsTable.tsx
  web/src/app/util/FilterContainer.js
  web/src/app/util/OtherActionsMobile.js
  web/src/app/util/SpeedDial.tsx
  web/src/app/util/avatars.tsx
  web/src/cypress/support/menu.ts
  web/src/package.json
  yarn.lock
Labels: size/s

#2881 Use temporary DB for db-schema make command
  Makefile
  migrate/schema.sql
Labels: size/xs

#2871 feat: add UI for chanWebhooks escalation policy step option
  graphql2/graphqlapp/escalationpolicy.go
  web/src/app/alerts/components/AlertDetails.tsx
  web/src/app/escalation-policies/PolicyStep.tsx
  web/src/app/escalation-policies/PolicyStepForm.js
  web/src/app/selection/ChanWebhookSelect.tsx
  web/src/app/selection/index.js
  web/src/app/util/Chips.tsx
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
Labels: size/m

#2886 ui/Time: increase underline offset
  web/src/app/util/Time.tsx
Labels: size/xs

#2880 ui: fix snackbar not showing latest alert notification
  web/src/app/alerts/AlertsList.tsx
  web/src/app/main/App.tsx
  web/src/app/main/SnackbarNotification.tsx
Labels: size/l

#2890 slack: fix DM display and pending state
  engine/compatmanager/db.go
  notification/slack/user.go
Labels: size/xs

#2891 add notices to services when nearing unackd alerts system limit
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/service.go
  graphql2/schema.graphql
  notice/queries.sql
  notice/store.go
  sqlc.yaml
  test/smoke/graphqlepnotices_test.go
  test/smoke/graphqlservicenotices_test.go
  web/src/app/alerts/AlertsList.tsx
  web/src/app/alerts/components/AlertDetails.tsx
  web/src/app/services/ServiceDetails.tsx
  web/src/app/services/ServiceMaintenanceNotice.tsx
  web/src/app/services/ServiceNotices.tsx
  web/src/schema.d.ts
Labels: size/l

#2894 dev: update sqlc to 1.17.2
  gadb/db.go
  gadb/models.go
  gadb/queries.sql.go
  sqlc.version
  swo/swodb/db.go
  swo/swodb/models.go
  swo/swodb/queries.sql.go
Labels: size/xs

#2897 mocktwilio/twiml: add initial doc.go, Say verb and NullInt types
  devtools/mocktwilio/twiml/doc.go
  devtools/mocktwilio/twiml/nullint.go
  devtools/mocktwilio/twiml/nullint_test.go
  devtools/mocktwilio/twiml/verbs.go
  devtools/mocktwilio/twiml/verbs_test.go
Labels: size/m

#2895 engine/statusmgr: cleanup old queries
  engine/statusmgr/db.go
Labels: size/s

#2912 mocktwilio/twiml: add remaining verbs
  devtools/mocktwilio/twiml/anyverb.go
  devtools/mocktwilio/twiml/gather.go
  devtools/mocktwilio/twiml/verbs.go
  devtools/mocktwilio/twiml/verbs_test.go
Labels: size/m

#2898 feat: adding error handlers to devtools
  devtools/genmake/run.go
  devtools/procwrap/main.go
  devtools/runproc/process.go
  devtools/sendit/readme_test.go
Labels: size/s

#2918 mocktwilio/twiml: Add Iterator for processing TwiML documents
  devtools/mocktwilio/twiml/iterator.go
  devtools/mocktwilio/twiml/iterator_test.go
Labels: size/m

#2913 testing: Move some service testing to playwright
  test/integration/service.spec.ts
  web/src/cypress/e2e/services.cy.ts
Labels: size/l

#2901 feat: adding error checking to the swo methods
  swo/swomsg/log.go
  swo/swosync/logicalsync.go
Labels: size/s

#2902 feat: adding error checking on misc packages
  migrate/migrate.go
  remotemonitor/monitor.go
  search/render.go
  util/jsonutil/merge.go
  validation/validate/jmespath_test.go
  validation/validate/phone_test.go
Labels: size/s

#2919 twilio: move version to api path instead of base
  devtools/mocktwilio/server.go
  notification/twilio/client.go
Labels: size/xs

#2904 feat: add error checks to engine methods
  engine/compatmanager/update.go
  engine/engine.go
  engine/message/db.go
Labels: size/s
