Repository target/goalert, pull requests merged in 2023-12, with the labels that each got.

#3499 graphql: Fix 500 errors on invalid JSON
  graphql2/graphqlapp/app.go
  test/smoke/graphqlerror_test.go
  test/smoke/harness/graphql.go
Labels: size/s

#3494 ui/profile: convert UserContactMethodVerificationForm to typescript
  web/src/app/users/UserContactMethodVerificationForm.tsx
Labels: size/s

#3514 search: fix handling of underscores and add contains match for names
  escalation/search.go
  notification/search.go
  schedule/rotation/search.go
  schedule/search.go
  search/render.go
  service/search.go
  user/search.go
Labels: size/s

#3512 ui/service: convert ServiceOnCallList to typescript
  web/src/app/lists/FlatList.tsx
  web/src/app/services/ServiceOnCallList.tsx
Labels: size/s

#3513 ui: splash screen from index.html
  Makefile
  web/index.html
  web/src/app/index.tsx
  web/src/app/main/NavBar.tsx
  web/src/app/main/WideSideBar.tsx
  web/src/app/main/components/Login.tsx
  web/src/app/public/logos/black/goalert-alt-logo.png
  web/src/app/public/logos/black/goalert-logo-original.png
  web/src/app/public/logos/black/goalert-logo-scaled.webp
  web/src/app/public/logos/black/goalert-logo-scaled@1.5.webp
  web/src/app/public/logos/black/goalert-logo-scaled@2.png
  web/src/app/public/logos/black/goalert-logo-scaled@2.webp
  web/src/app/public/logos/darkmode_logo.svg
  web/src/app/public/logos/lightmode_logo.svg
  web/src/app/public/logos/lightmode_logo_full.svg
  web/src/app/public/logos/white/goalert-alt-logo-white.png
  web/src/app/public/logos/white/goalert-logo-white-scaled.webp
  web/src/app/public/logos/white/goalert-logo-white-scaled@1.5.webp
  web/src/app/public/logos/white/goalert-logo-white-scaled@2.png
  web/src/app/public/logos/white/goalert-logo-white-scaled@2.webp
  web/src/app/styles/index.tsx
  web/src/app/styles/loading.css
  web/src/global.d.ts
Labels: size/l

#3526 ui: update calendar version - fixing invalid ref with invalid scrollHeight
  package.json
  yarn.lock
Labels: size/xs

#3533 dev: Split GraphQL schema into multiple files
  devtools/gqltsgen/run.go
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graph/_Mutation.graphqls
  graphql2/graph/_Query.graphqls
  graphql2/graph/_directives.graphqls
  graphql2/graph/gqlapikeys.graphqls
  graphql2/schema.go
  graphql2/schema.graphql
  web/src/genschema.go
  web/src/schema.d.ts
Labels: size/xl

#3532 fix: add missing typenames
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/users/UserContactMethodVerificationDialog.tsx
Labels: size/s

#3547 dev: add missing deps to makefile targets
  Makefile
Labels: size/xs

#3558 ui: Markdown timestamp support
  package.json
  web/src/app/util/CopyText.tsx
  web/src/app/util/Markdown.js
  web/src/app/util/Markdown.timestampSupport.tsx
  yarn.lock
Labels: size/s

#3548 graphql: add `destinationTypes` and `destinationFieldValidate` queries
  expflag/flags.go
  graphql2/generated.go
  graphql2/graph/_directives.graphqls
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/directives.go
  graphql2/models_gen.go
  web/src/expflag.d.ts
  web/src/schema.d.ts
Labels: size/l

#3560 dev: add playwright component tests
  .gitignore
  .yarnrc.yml
  Makefile
  package.json
  playwright-ct.config.ts
  playwright.config.ts
  playwright/index.html
  playwright/index.tsx
  playwright/playwright-ct.bin.js
  playwright/playwright-e2e.bin.js
  tsconfig.json
  web/src/app/util/TelTextField.ct-spec.tsx
  web/src/app/util/TelTextField.story.tsx
  web/src/app/util/TelTextField.tsx
  yarn.lock
Labels: size/m
