Repository target/goalert, pull requests merged in 2023-04, with the labels that each got.

#2923 auth/basic: lower bcrypt difficulty, limit 1 compare at a time
  auth/basic/db.go
Labels: size/s

#2924 ctxlock: add IDLocker and tests
  ctxlock/config.go
  ctxlock/idlocker.go
  ctxlock/idlocker_test.go
  ctxlock/lock.go
  ctxlock/unlock.go
Labels: size/l

#2925 http: Replace ConcurrencyLimiter with IDLocker
  app/inithttp.go
  app/limitconcurrencybyauthsource.go
  app/middlewarereqlimit.go
  auth/basic/identityprovider.go
  auth/basic/provider.go
  ctxlock/idlocker_test.go
  util/errutil/httperror.go
Labels: size/l

#2927 feat: add markdown supported hint, increased description size to 6KiB for service form
  service/service.go
  web/src/app/forms/FormField.js
  web/src/app/services/ServiceForm.tsx
Labels: size/s

#2899 feat: adding error checks to tests folder
  test/smoke/harness/harness.go
  test/smoke/migrations_test.go
Labels: size/s

#2900 feat: adding error checks to notification methods
  notification/email/sendmail.go
  notification/slack/servemessageaction.go
  notification/twilio/signature.go
  notification/twilio/validation.go
Labels: size/s

#2416 ui/schedules: remove tz filter and add local time hover on ScheduleShiftList
  test/integration/schedules.spec.ts
  test/integration/timepickers.spec.ts
  web/src/app/lists/FlatListItem.tsx
  web/src/app/schedules/ScheduleShiftList.tsx
  web/src/app/schedules/useScheduleTZ.ts
  web/src/cypress/e2e/timepickers.cy.ts
Labels: size/l

#2896 ui/Time: use Time component for calendar subs and on-call form
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/users/UserCalendarSubscriptionList.tsx
Labels: size/s

#2942 dev: use ipv4-only addresses for Cypress
  Procfile.cypress
  Procfile.cypress.ci
  Procfile.cypress.prod
Labels: size/s

#2936 ui/AlertDetailPage: Convert to typescript
  web/src/app/alerts/pages/AlertDetailPage.tsx
Labels: size/xs

#2933 feat: clarify permissions around contact methods
  web/src/app/users/UserContactMethodList.tsx
  web/src/app/util/OtherActions.js
  web/src/app/util/OtherActionsDesktop.js
Labels: size/s

#2945 auth/github: prevent cryptic error on no name set
  auth/github/identityprovider.go
Labels: size/xs

#2939 ui/alerts: Convert alert step content to typescript
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertConfirm.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertInfo.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertListItem.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertReview.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceListItem.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceSelect.tsx
  web/src/app/forms/FormField.js
  web/src/app/services/ServiceFilterContainer.tsx
  web/src/app/services/ServiceForm.tsx
Labels: size/m

#2950 dev: Go updates apr 2023
  go.mod
  go.sum
  graphql2/models_gen.go
  pkg/sysapi/sysapi.pb.go
Labels: size/l

#2952 Update eslint deps
  package.json
  yarn.lock
Labels: size/xs

#2953 dev/ui: Update prettier & stylelint
  package.json
  web/src/app/admin/admin-alert-counts/AlertCountLineGraph.tsx
  web/src/app/services/AlertMetrics/AlertAveragesGraph.tsx
  web/src/app/services/AlertMetrics/AlertCountGraph.tsx
  web/src/app/worker/methods.ts
  yarn.lock
Labels: size/xs

#2951 dev: add models_gen.go to labeler ignore list
  .github/workflows/labeler.yml
Labels: size/xs

#2954 dev/ui: update most react deps
  web/src/package.json
  yarn.lock
Labels: size/s

#2944 dev: fix "Command not found" noise
  Makefile
Labels: size/xs

#2928 codeql: Create .github/workflows/codeql.yml
  .github/workflows/codeql.yml
Labels: size/s

#2934 dev: Single package.json
  .github/workflows/main.yml
  .gitignore
  Makefile
  Makefile.binaries.mk
  Procfile
  Procfile.cypress
  Procfile.cypress.ci
  Procfile.cypress.prod
  Procfile.integration
  Procfile.prod
  Procfile.swo
  cypress.config.ts
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/genmake/template.mk
  package.json
  web/src/esbuild.config.js
  web/src/esbuild.cypress.js
  web/src/genschema.go
  web/src/package.json
Labels: size/m

#2935 ui/AlertDetailLogs: Convert to typescript
  web/src/app/alerts/AlertDetailLogs.tsx
Labels: size/s

#2931 yarn: use version 3.5.0 with corepack and pnp
  .github/workflows/main.yml
  .gitignore
  Makefile
  Procfile.cypress
  Procfile.cypress.ci
  Procfile.cypress.prod
  cypress.config.js
  devtools/ci/tasks/build-all.yml
  package.json
  tsconfig.json
  web/src/app/admin/AdminNumberLookup.tsx
  web/src/app/admin/AdminSMSSend.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertForm.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceSelect.tsx
  web/src/app/services/ServiceFilterContainer.tsx
  web/src/app/services/ServiceLabelCreateDialog.tsx
  web/src/app/services/ServiceLabelEditDialog.tsx
  web/src/esbuild.cypress.js
  web/src/genschema.go
  yarn.lock
Labels: size/m

#2970 dev: enable vscode sdk
  Makefile
  docs/development-setup.md
Labels: size/s

#2971 certs: move default values to Go vars
  app/cmdcerts.go
Labels: size/s

#2972 chore: update cypress eslint plugin
  package.json
  web/src/cypress/e2e/alerts.cy.ts
  web/src/cypress/e2e/calendarSubscriptions.cy.ts
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
  web/src/cypress/e2e/favorites.cy.ts
  web/src/cypress/e2e/materialSelect.cy.ts
  web/src/cypress/e2e/rotations.cy.ts
  web/src/cypress/support/form.ts
  web/src/cypress/support/page-fab.ts
  web/src/cypress/support/page-search.ts
  web/src/cypress/support/select-by-label.ts
  yarn.lock
Labels: size/m

#2715 ui: move create button on main list pages
  test/integration/schedules.spec.ts
  test/integration/timepickers.spec.ts
  web/src/app/admin/admin-message-logs/AdminDebugMessagesLayout.tsx
  web/src/app/alerts/AlertsList.tsx
  web/src/app/alerts/CreateAlertDialog/CreateAlertDialog.tsx
  web/src/app/escalation-policies/PolicyList.tsx
  web/src/app/lists/ControlledPaginatedList.tsx
  web/src/app/lists/QueryList.tsx
  web/src/app/lists/SimpleListPage.tsx
  web/src/app/rotations/RotationList.tsx
  web/src/app/schedules/ScheduleList.tsx
  web/src/app/services/ServiceAlerts.tsx
  web/src/app/services/ServiceList.tsx
  web/src/app/users/UserList.tsx
  web/src/cypress/e2e/alerts.cy.ts
  web/src/cypress/e2e/escalationPolicies.cy.ts
  web/src/cypress/e2e/favorites.cy.ts
  web/src/cypress/e2e/materialSelect.cy.ts
  web/src/cypress/e2e/rotations.cy.ts
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/l

#2973 dev: playwright tweaks
  Makefile
  playwright.config.ts
Labels: size/xs

#2926 slack: update user-group membership for configured schedules
  app/initslack.go
  notification/desttype.go
  notification/desttype_string.go
  notification/slack/usergrouperror.go
  notification/slack/usergroupsender.go
Labels: size/l

#2974 app: remove old concurrencylimiter code
  app/concurrencylimiter.go
  app/concurrencylimiter_test.go
Labels: size/l

#2903 feat: adding error checks to app methods
  app/cmd.go
  app/initauth.go
  app/lifecycle/manager_test.go
  app/prometheus.go
  app/shutdown.go
  app/trigger.go
  auth/authtoken/token_test.go
Labels: size/m
