Repository target/goalert, pull requests merged in 2023-06, with the labels that each got.

#3060 fix slack dm status updates
  engine/message/db.go
  graphql2/graphqlapp/user.go
  test/smoke/slackdm2889_test.go
  test/smoke/statusupdatescancel_test.go
  user/store.go
  user/user.go
Labels: size/m

#3046 feat: on call notification channel separation
  Makefile
  notification/slack/usergrouperror.go
  notification/slack/usergroupsender.go
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/schedules/on-call-notifications/hooks.ts
  web/src/app/schedules/on-call-notifications/util.ts
  web/src/app/selection/SlackUserGroupSelect.tsx
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/l

#3072 ui/profile: fix test message dialog
  web/src/app/users/SendTestDialog.tsx
Labels: size/s

#3071 expflag: remove slack-dm flag
  app/initslack.go
  devtools/mockslack/server.go
  devtools/mockslack/teaminfo.go
  engine/compatmanager/update.go
  expflag/flags.go
  graphql2/graphqlapp/contactmethod.go
  test/smoke/slackdm2889_test.go
  test/smoke/slackdm_test.go
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/users/UserContactMethodForm.tsx
  web/src/app/users/UserContactMethodList.tsx
  web/src/expflag.d.ts
Labels: size/s

#3036 feat: webhook on call notification
  .github/workflows/labeler.yml
  .github/workflows/main.yml
  graphql2/graphqlapp/mutation.go
  graphql2/graphqlapp/schedule.go
  notification/webhook/sender.go
  web/src/app/icons/components/Icons.js
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
Labels: size/m

#3074 go: update Go to 1.20.5
  devtools/ci/dockerfiles/build-env/Dockerfile
  devtools/ci/dockerfiles/goalert/Dockerfile
  devtools/ci/tasks/build-all.yml
  devtools/ci/tasks/build-binaries.yml
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/ci/tasks/test-smoketest.yml
Labels: size/xs

#2991 ui/user: Allow setting/changing basic auth passwords in UI
  user/store.go
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserEditDialog.tsx
  web/src/app/users/UserEditForm.tsx
  web/src/cypress/e2e/users.cy.ts
Labels: size/xl

#2481 ui/admin: add message logs notification count line graph
  notification/search.go
  web/src/app/admin/admin-message-logs/AdminMessageLogsControls.tsx
  web/src/app/admin/admin-message-logs/AdminMessageLogsGraph.tsx
  web/src/app/admin/admin-message-logs/AdminMessageLogsLayout.tsx
  web/src/app/admin/admin-message-logs/util.ts
  web/src/app/lists/QueryList.tsx
  web/src/app/users/UserList.tsx
  web/src/app/util/ISOPickers.tsx
  web/src/app/util/Search.js
  web/src/app/worker/index.ts
  web/src/app/worker/methods.ts
  web/src/cypress/e2e/admin.cy.ts
Labels: size/xl

#3073 sms: Allow multi-segment messages
  notification/twilio/alertsms.go
  notification/twilio/alertsms_test.go
  notification/twilio/sms.go
Labels: size/m

#3089 ui: move button for adding user to rotation
  web/src/app/rotations/RotationDetails.tsx
  web/src/app/rotations/RotationUserList.tsx
  web/src/cypress/e2e/materialSelect.cy.ts
  web/src/cypress/e2e/rotations.cy.ts
Labels: size/s

#3091 ui: update button styling on profile
  test/integration/email-cm.spec.ts
  web/src/app/users/UserContactMethodList.tsx
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserNotificationRuleList.tsx
  web/src/cypress/e2e/profile.cy.ts
Labels: size/s

#3090 ui: move button creating a step on an EP
  web/src/app/escalation-policies/PolicyDetails.tsx
  web/src/app/escalation-policies/PolicyStepsCard.js
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
  web/src/cypress/e2e/favorites.cy.ts
  web/src/cypress/e2e/materialSelect.cy.ts
Labels: size/m

#3111 auth: set SameSite to strict on session cookie
  auth/cookies.go
Labels: size/xs

#3114 auth: Validate redir on return from auth
  auth/handler.go
  playwright.config.ts
  test/integration/oidc.spec.ts
Labels: size/s

#3113 dev: Remove dead code
  alert/alertlog/legacysearch.go
  alert/alertlog/store.go
  alert/legacysearch.go
  alert/store.go
  app/app.go
  app/apptime.go
  app/cmd.go
  app/config.go
  app/cooldown.go
  app/inithttp.go
  app/shutdown.go
  assignment/assignment.go
  assignment/source.go
  assignment/srctype.go
  assignment/srctype_string.go
  docs/getting-started.md
  schedule/rotation/store.go
  schedule/rule/store.go
  service/legacysearch.go
  service/store.go
  test/smoke/harness/harness.go
  test/smoke/harness/slack.go
  user/contactmethod/contactmethod.go
  user/contactmethod/store.go
  user/contactmethod/type.go
  user/notificationrule/store.go
  user/store.go
  user/user.go
  util/alignedticker.go
  util/contextcache.go
  util/contextcache_test.go
  util/contextroundtripper.go
  util/contextwaitgroup.go
Labels: size/xl

#3115 dev: hardening some of the dev tools and a few places in app code
  devtools/configparams/run.go
  devtools/mockslack/oauthauthorize.go
  devtools/mockslack/oauthauthorize.html
  devtools/mockslack/server.go
  devtools/mockslack/user.go
  devtools/procwrap/main.go
  graphql2/mapconfig.go
  schedule/oncallnotificationrule.go
  web/src/app/util/query_param.js
Labels: size/m

#3041 Add code coverage targets for backend code
  .gitignore
  Makefile
  Makefile.binaries.mk
  Procfile.cypress
  Procfile.cypress.ci
  Procfile.cypress.prod
  devtools/genmake/template.mk
  playwright.config.ts
  test/integration/setup/global-teardown.ts
Labels: size/m

#3128 js: update dependencies
  package.json
  web/src/app/admin/admin-alert-counts/AlertCountLineGraph.tsx
  web/src/app/admin/admin-message-logs/AdminMessageLogsGraph.tsx
  web/src/app/services/AlertMetrics/AlertAveragesGraph.tsx
  web/src/app/services/AlertMetrics/AlertCountGraph.tsx
  yarn.lock
Labels: size/s

#3127 go: update dependencies
  gadb/db.go
  gadb/models.go
  gadb/queries.sql.go
  go.mod
  go.sum
  graphql2/generated.go
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
  protoc.version
  sqlc.version
  swo/swodb/db.go
  swo/swodb/models.go
  swo/swodb/queries.sql.go
Labels: size/xs

#3135 playwright: run playwright install before test commands
  Makefile
Labels: size/xs

#3129 feat: add integration test for slack usergroup feat
  devtools/mockslack/api.go
  devtools/mockslack/cmd/mockslack/main.go
  devtools/mockslack/server.go
  devtools/mockslack/state.go
  devtools/mockslack/usergroupslist.go
  devtools/mockslack/util.go
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/selection/SlackUserGroupSelect.tsx
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/m

#3132 go: update dependencies with major-version updates
  app/cmd.go
  auth/authlink/store.go
  auth/github/identityprovider.go
  devtools/sendit/readme_test.go
  devtools/sendit/token.go
  go.mod
  go.sum
  keyring/store.go
Labels: size/s
