Repository target/goalert, pull requests merged in 2023-09, with the labels that each got.

#3256 swo: add missing id column to alert_feedback
  Makefile
  gadb/models.go
  gadb/queries.sql.go
  migrate/migrations/20230831141312-alert-feedback-id.sql
  migrate/schema.sql
  playwright.config.ts
  test/integration/switchover.spec.ts
Labels: size/s

#3254 feat: add google analytics support
  config/config.go
  graphql2/mapconfig.go
  package.json
  validation/validate/analytics.go
  web/src/app/alerts/AlertsList.tsx
  web/src/app/alerts/components/AlertDetails.tsx
  web/src/app/main/App.tsx
  yarn.lock
Labels: size/s

#3258 db: switch driver to pgx5
  app/listenevents.go
  go.mod
  go.sum
  migrate/migrate.go
  sqlc.yaml
  swo/connector.go
  swo/executor.go
  swo/manager.go
  swo/swodb/db.go
  swo/swodb/models.go
  swo/swodb/queries.sql.go
  swo/swoinfo/conninfo.go
  swo/swoinfo/db.go
  swo/swoinfo/scansequences.go
  swo/swoinfo/scantables.go
  swo/swomsg/log.go
  swo/swosync/initialsync.go
  swo/swosync/logicalreplicator.go
  swo/swosync/logicalsync.go
  swo/swosync/sequencesync.go
  swo/swosync/tablesync.go
  test/smoke/harness/harness.go
  test/smoke/harness/sql.go
  test/smoke/migrations_test.go
  util/sqldrv/connector.go
  util/sqlutil/error.go
  util/sqlutil/listener.go
  util/sqlutil/quoteid.go
  util/sqlutil/rollback.go
Labels: size/m

#3264 ep: fix webhook expansion when slack is disabled
  web/src/app/escalation-policies/PolicyStepForm.js
Labels: size/xs

#3266 dev: add local db url to dev setup guide
  docs/development-setup.md
Labels: size/xs

#3272 timeutil: preserve field/type information when parsing ISODuration
  graphql2/graphqlapp/alert.go
  graphql2/graphqlapp/messagelog.go
  util/timeutil/isoduration.go
  util/timeutil/isoduration_test.go
  util/timeutil/isorinterval.go
  util/timeutil/isorinterval_test.go
Labels: size/m

#3273 dev: resolve circular dependency in make db-schema target
  Makefile
  devtools/pgdump-lite/sqlc.yaml
  devtools/psql-lite/main.go
  migrate/cmd/goalert-migrate/main.go
  sqlc.yaml
  test/smoke/harness/sql.go
  test/smoke/harness/sql_test.go
  util/sqlutil/splitquery.go
  util/sqlutil/splitquery_test.go
Labels: size/l

#3275 dev: update linter to use version of Go used by project
  .github/workflows/golangci-lint.yml
Labels: size/xs

#3276 graphql: add `listGQLFields` query
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graphqlapp/query.go
  graphql2/graphqlapp/user.go
  graphql2/models_gen.go
  graphql2/schema.go
  graphql2/schema.graphql
  web/src/schema.d.ts
Labels: size/m

#3277 jest: normalize whitespace before comparing timestamps
  web/src/app/util/timeFormat.test.ts
Labels: size/xs

#3243 feat: add monthly rotation option
  devtools/pgmocktime/mocker.go
  devtools/resetdb/datagen.go
  gadb/models.go
  graphql2/generated.go
  graphql2/graphqlapp/rotation.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  migrate/migrations/20230911153243-add-monthly-rotation.sql
  migrate/schema.sql
  schedule/rotation/rotation.go
  schedule/rotation/rotation_test.go
  schedule/rotation/type.go
  test/smoke/harness/graphql.go
  test/smoke/rotationmonthly_test.go
  web/src/app/rotations/HandoffSummary.tsx
  web/src/app/rotations/RotationForm.tsx
  web/src/schema.d.ts
Labels: size/l

#3279 dev: Update binary tool versions
  devtools/ci/dockerfiles/build-env/Dockerfile
  devtools/ci/dockerfiles/goalert/Dockerfile
  devtools/ci/tasks/build-all.yml
  devtools/ci/tasks/build-binaries.yml
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/ci/tasks/test-smoketest.yml
  gadb/db.go
  gadb/models.go
  gadb/queries.sql.go
  golangci-lint.version
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
  prometheus.version
  protoc.version
  sqlc.version
  swo/swodb/db.go
  swo/swodb/models.go
  swo/swodb/queries.sql.go
Labels: size/s

#3280 dev: increase linter timeout
  .github/workflows/golangci-lint.yml
Labels: size/xs

#3281 dev: Update go deps
  auth/github/identityprovider.go
  go.mod
  go.sum
Labels: size/xs

#3274 api: add base admin API key support
  apikey/context.go
  apikey/jwt.go
  apikey/lastused.go
  apikey/policy.go
  apikey/policyinfo.go
  apikey/queries.sql
  apikey/store.go
  app/app.go
  app/initauth.go
  app/initgraphql.go
  app/initstores.go
  auth/handler.go
  auth/handlerconfig.go
  expflag/flags.go
  gadb/models.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/gqlapikeys.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  migrate/migrations/20230913170424-graphql-api-key.sql
  migrate/schema.sql
  permission/source.go
  permission/sourcetype_string.go
  sqlc.yaml
  validation/validate/oneof.go
  web/src/expflag.d.ts
  web/src/schema.d.ts
Labels: size/xl

#3293 chore: integration keys sqlc
  app/initstores.go
  devtools/pgdump-lite/pgd/db.go
  devtools/pgdump-lite/pgd/models.go
  devtools/pgdump-lite/pgd/queries.sql.go
  gadb/queries.sql.go
  graphql2/graphqlapp/integrationkey.go
  graphql2/graphqlapp/mutation.go
  integrationkey/queries.sql
  integrationkey/store.go
  sqlc.yaml
  validation/validate/uuid.go
  validation/validate/uuid_test.go
Labels: size/l

#3292 apikey: add list and update of graphql api keys
  apikey/queries.sql
  apikey/store.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/gqlapikeys.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  web/src/schema.d.ts
Labels: size/l

#3291 apikey: cache policy info lookup & last usage updates
  apikey/lastusedcache.go
  apikey/polcache.go
  apikey/store.go
Labels: size/m

#3278 timezone: Use canonical zone names
  .github/workflows/labeler.yml
  Makefile
  timezone/aliases.txt
  timezone/search.go
  timezone/zones.go
  timezone/zones.txt
  util/loadlocation.go
Labels: size/m

#3312 apikey: add role to gql api key info
  apikey/store.go
  graphql2/generated.go
  graphql2/graphqlapp/gqlapikeys.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  web/src/schema.d.ts
Labels: size/xs

#3311 feat: signal queue logic
  app/app.go
  app/inithttp.go
  app/initstores.go
  gadb/queries.sql.go
  go.mod
  go.sum
  notifyapi/config.go
  notifyapi/notify.go
  notifyapi/rule.go
  service/rule/queries.sql
  service/rule/store.go
  signal/queries.sql
  signal/signal.go
  signal/store.go
  sqlc.yaml
Labels: size/l

#3315 chore: rename notify to signal
  alert/alert.go
  alert/alertlog/legacylogs.go
  alert/alertlog/store.go
  alert/source.go
  app/inithttp.go
  auth/handler.go
  devtools/resetdb/datagen.go
  gadb/models.go
  graphql2/graphqlapp/config.go
  graphql2/graphqlapp/integrationkey.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  integrationkey/integrationkey.go
  integrationkey/store.go
  integrationkey/type.go
  migrate/migrations/20230919105616-create-signal-tables.sql
  migrate/schema.sql
  signalapi/config.go
  signalapi/notify.go
  signalapi/rule.go
  web/src/app/wizard/WizardForm.js
  web/src/cypress/support/service.ts
  web/src/schema.d.ts
Labels: size/m

#3265 mark many alerts as noise from alerts list
  alert/queries.sql
  alert/store.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/alert.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  web/src/app/alerts/AlertsList.tsx
  web/src/app/alerts/components/AlertFeedback.tsx
  web/src/app/alerts/components/AlertFeedbackDialog.tsx
  web/src/cypress/e2e/alerts.cy.ts
  web/src/schema.d.ts
Labels: size/l
