Repository target/goalert, pull requests merged in 2024-04, with the labels that each got.

#3774 test/smoke: add migratetest package
  test/smoke/migratetest/copyscanner.go
  test/smoke/migratetest/copyscanner_test.go
  test/smoke/migratetest/ruleset.go
  test/smoke/migratetest/snapshot.go
  test/smoke/migratetest/tablesnapshot.go
  test/smoke/migratetest/tablesnapshot_test.go
Labels: size/l

#3786 dev: ignore deleted files when calculating pr size
  .github/workflows/labeler.yml
Labels: size/xs

#3764 Add alert metadata
  alert/alert.go
  alert/metadata.go
  alert/queries.sql
  alert/store.go
  engine/sendmessage.go
  gadb/models.go
  gadb/queries.sql.go
  genericapi/handler.go
  graphql2/generated.go
  graphql2/graphqlapp/alert.go
  graphql2/graphqlapp/dataloaders.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  migrate/migrations/20240212125328-alert-metadata.sql
  migrate/schema.sql
  notification/alert.go
  notification/webhook/sender.go
  permission/context.go
  test/smoke/alertmetadata_test.go
  web/src/app/documentation/sections/IntegrationKeys.md
  web/src/app/documentation/sections/Webhooks.md
  web/src/schema.d.ts
Labels: size/l

#3779 dest: Destination display error handling
  Makefile
  devtools/gqltsgen/run.go
  graphql2/generated.go
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/models_gen.go
  notification/slack/channel.go
  notification/slack/user.go
  web/src/app/escalation-policies/PolicyStepEditDialogDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepsQuery.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.tsx
  web/src/app/selection/DestinationSearchSelect.stories.tsx
  web/src/app/selection/DestinationSearchSelect.tsx
  web/src/app/users/UserContactMethodEditDialogDest.stories.tsx
  web/src/app/users/UserContactMethodEditDialogDest.tsx
  web/src/app/users/UserContactMethodListDest.stories.tsx
  web/src/app/users/UserContactMethodListDest.tsx
  web/src/app/users/UserNotificationRuleListDest.tsx
  web/src/app/util/DestinationChip.tsx
  web/src/app/util/DestinationInputChip.tsx
  web/src/schema.d.ts
Labels: size/l

#3794 engine/statusmgr: Skip status updates without an associated log entry
  app/cmd.go
  engine/statusmgr/db.go
  engine/statusmgr/queries.sql
  engine/statusmgr/update.go
  gadb/queries.sql.go
  test/smoke/statusupdatesnolog_test.go
Labels: size/m

#3796 ts: convert PolicyStepCard to ts
  web/src/app/escalation-policies/PolicyStepsCard.tsx
  web/src/app/escalation-policies/stepUtil.tsx
Labels: size/s

#3800 ui/config: always request dest types
  web/src/app/selection/DestinationInputDirect.tsx
  web/src/app/selection/DestinationSearchSelect.tsx
  web/src/app/util/RequireConfig.tsx
Labels: size/s

#3792 gql-api-keys: only setState once when duplicating key
  web/src/app/admin/admin-api-keys/AdminAPIKeyCreateDialog.tsx
Labels: size/s

#3797 gql-api-keys: Takes GQL API keys out of experimental state
  auth/handler.go
  expflag/flags.go
  graphql2/graphqlapp/gqlapikeys.go
  test/integration/gqlapikeys.spec.ts
  test/smoke/gqlapikeys_test.go
  web/src/app/main/NavBar.tsx
  web/src/expflag.d.ts
Labels: size/s

#3799 ep: switch policy steps to use urql
  web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
  web/src/app/escalation-policies/PolicyStepsCard.tsx
  web/src/app/escalation-policies/PolicyStepsQuery.tsx
  web/src/app/escalation-policies/stepUtil.tsx
  web/src/app/rotations/util.tsx
Labels: size/m

#3815 service maint: allow specifying a custom end time
  web/src/app/services/ServiceMaintenanceDialog.tsx
  web/src/app/util/ISOPickers.tsx
Labels: size/s

#3784 dev: refactor migrations_test to use new migrationtest package
  go.mod
  go.sum
  test/smoke/migrations_test.go
Labels: size/l

#3817 dev: update ui dependencies
  package.json
  yarn.lock
Labels: size/xs

#3790 profile: fix flicker when opening dialogs
  web/src/app/users/UserContactMethodList.tsx
  web/src/app/users/UserContactMethodListDest.tsx
Labels: size/m

#3824 playwright: Fix tooltip hover check
  test/integration/schedules.spec.ts
  web/src/app/schedules/ScheduleShiftList.tsx
Labels: size/s

#3822 urql: convert remaining schedule files to urql
  web/src/app/schedules/ScheduleRuleDeleteDialog.tsx
  web/src/app/schedules/ScheduleShiftList.tsx
  web/src/app/schedules/ScheduleTZFilter.jsx
  web/src/app/schedules/useOverrideNotices.ts
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/s

#3823 urql: Convert UserList to use urql
  web/src/app/lists/FlatListItem.tsx
  web/src/app/lists/ListPageControls.tsx
  web/src/app/lists/PaginatedList.tsx
  web/src/app/users/UserList.tsx
  web/src/app/util/AppLink.tsx
  web/src/app/util/pagination.ts
  web/src/cypress/e2e/favorites.cy.ts
  web/src/cypress/e2e/users.cy.ts
Labels: size/l

#3778 univ-keys: add Expr <-> Condition support
  expflag/flags.go
  go.mod
  go.sum
  graphql2/generated.go
  graphql2/graph/errorcodes.graphqls
  graphql2/graph/expr.graphqls
  graphql2/graphqlapp/expr.go
  graphql2/graphqlapp/expr_test.go
  graphql2/models_gen.go
  web/src/app/util/errtypes.ts
  web/src/expflag.d.ts
  web/src/schema.d.ts
Labels: size/l
