Repository target/goalert, pull requests merged in 2024-07, with the labels that each got.

#3948 engine/message: start migrating to sqlc
  engine/message/db.go
  engine/message/message.go
  engine/message/queries.sql
  gadb/db.go
  gadb/models.go
  gadb/queries.sql.go
  notification/desttype.go
  notification/messagetype.go
  sqlc.version
  sqlc.yaml
  swo/swodb/db.go
  swo/swodb/models.go
  swo/swodb/queries.sql.go
Labels: size/m

#3950 uik: Add ability to edit and manage rules
  test/integration/uik.spec.ts
  web/src/app/services/UniversalKey/UniversalKeyPage.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleConfig.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleCreateDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleEditDialog.tsx
Labels: size/l

#3949 Refactor notification channels handling
  gadb/queries.sql.go
  notificationchannel/channel.go
  notificationchannel/queries.sql
  notificationchannel/store.go
  sqlc.yaml
Labels: size/m

#3958 update go deps
  cmd/goalert-slack-email-sync/main.go
  go.mod
  go.sum
  pkg/sysapi/client_test.go
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
Labels: size/xs

#3959 uik: Add `pending_signals` table
  gadb/dest.go
  gadb/models.go
  gadb/queries.sql.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/maplimit.go
  integrationkey/config.go
  integrationkey/queries.sql
  integrationkey/uik.go
  integrationkey/uik/compilerule.go
  integrationkey/uik/handler.go
  limit/id.go
  migrate/migrations/20240702104907-signals-limit-key.sql
  migrate/migrations/20240702105107-pending-signals.sql
  migrate/schema.sql
  util/errutil/httperror.go
  util/errutil/limiterror.go
Labels: size/l

#3960 uik: Enhance channel creation and rule compilation
  gadb/queries.sql.go
  integrationkey/config.go
  integrationkey/queries.sql
  integrationkey/uik/compilerule.go
  integrationkey/uik/compilerule_test.go
Labels: size/s

#3853 urql: move schedule override list to ListPageControls
  web/src/app/schedules/ScheduleOverrideList.jsx
Labels: size/m

#3854 urql: move admin message logs to ListPageControls
  web/src/app/admin/admin-message-logs/AdminMessageLogsLayout.tsx
  web/src/app/lists/ListPageControls.tsx
  web/src/cypress/e2e/admin.cy.ts
Labels: size/s

#3971 engine: fix for notification channel deduplication migration
  engine/schedulemanager/db.go
  engine/schedulemanager/queries.sql
  engine/schedulemanager/scheduledata.go
  engine/schedulemanager/state.go
  engine/schedulemanager/update.go
  gadb/models.go
  gadb/queries.sql.go
  migrate/migrations/20240628135216-dedup-notif-channels.sql
  migrate/migrations/20240708153641-nc-duplicate-table.sql
  migrate/schema.sql
  sqlc.yaml
  test/smoke/migrations_test.go
  test/smoke/ncdedup_test.go
Labels: size/l

#3973 dest: Refactor param handling and standardize field names
  graphql2/graphqlapp/destinationtypes.go
  integrationkey/uik/handler.go
  migrate/migrations/20240709094902-underscore-fields-cm.sql
  migrate/migrations/20240709094903-underscore-fields-nr.sql
  migrate/schema.sql
  test/integration/email-cm.spec.ts
  test/integration/first-login.spec.ts
  test/smoke/harness/harness.go
  test/smoke/ncdedup_test.go
  test/smoke/signal_test.go
  web/src/app/escalation-policies/PolicyStepCreateDialog.stories.tsx
  web/src/app/escalation-policies/PolicyStepEditDialog.stories.tsx
  web/src/app/escalation-policies/PolicyStepForm.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.stories.tsx
  web/src/app/selection/DestinationField.stories.tsx
  web/src/app/selection/DestinationInputDirect.stories.tsx
  web/src/app/services/UniversalKey/UniversalKeysActionsForm.stories.tsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/users/UserContactMethodCreateDialog.stories.tsx
  web/src/app/users/UserContactMethodEditDialog.stories.tsx
  web/src/app/users/UserContactMethodForm.stories.tsx
  web/src/app/users/UserContactMethodList.stories.tsx
  web/src/app/util/DestinationInputChip.stories.tsx
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
  web/src/cypress/e2e/favorites.cy.ts
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/l

#3974 ErrorConsumer: Support function-based error handling and cleanup
  web/src/app/dialogs/FormDialog.jsx
  web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyActionsForm.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleCreateDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleEditDialog.tsx
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/users/UserContactMethodEditDialog.tsx
  web/src/app/util/ErrorConsumer.ts
Labels: size/s

#3975 engine/signal: Add signal manager module and support for sending signal messages
  engine/engine.go
  engine/message/db.go
  engine/message/queue.go
  engine/processinglock/type.go
  engine/queries.sql
  engine/sendmessage.go
  engine/signalmgr/db.go
  engine/signalmgr/queries.sql
  engine/signalmgr/update.go
  gadb/models.go
  gadb/queries.sql.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/integrationkey.go
  integrationkey/config.go
  migrate/migrations/20240709134232-incr-message-vers.sql
  migrate/migrations/20240709134305-signal-module.sql
  migrate/migrations/20240709134405-signal-message-type.sql
  migrate/schema.sql
  notification/messagetype.go
  notification/messagetype_string.go
  notification/signal.go
  notification/slack/channel.go
  sqlc.yaml
  test/smoke/signal_test.go
Labels: size/l

#3976 uik: Add `defaultValue` to dynamic action params
  graphql2/generated.go
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/destinationtypes.go
  graphql2/models_gen.go
  web/src/app/selection/DynamicActionForm.stories.tsx
  web/src/app/selection/DynamicActionForm.tsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/util/RequireConfig.tsx
  web/src/schema.d.ts
Labels: size/s

#3978 uik: Refactor config to use specific UIK types
  gadb/dest.go
  gadb/models.go
  gadb/queries.sql.go
  gadb/uikconfig.go
  go.mod
  go.sum
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationvalidation.go
  graphql2/graphqlapp/integrationkey.go
  graphql2/models_gen.go
  graphql2/uuid.go
  integrationkey/config.go
  integrationkey/store.go
  integrationkey/uik/compilerule.go
  integrationkey/uik/compilerule_test.go
  integrationkey/uik/handler.go
  notification/signal.go
  notification/slack/channel.go
  sqlc.yaml
  test/smoke/signal_test.go
Labels: size/l

#3979 notification/dest: refactor to allow future map values
  devtools/resetdb/datagen.go
  devtools/resetdb/main.go
  engine/backend.go
  engine/callback.go
  engine/engine.go
  engine/isknowndest.go
  engine/message/db.go
  engine/message/dedupalerts_test.go
  engine/message/queue_test.go
  engine/message/throttle.go
  engine/queries.sql
  engine/sendmessage.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/dataloaders.go
  graphql2/graphqlapp/messagelog.go
  graphql2/graphqlapp/notificationrule.go
  graphql2/graphqlapp/schedule.go
  notification/destcompat.go
  notification/desttype.go
  notification/search.go
  notification/store.go
  notification/twilio/client_test.go
  notification/twilio/voice_test.go
  notificationchannel/channel.go
  test/smoke/harness/harness.go
  user/contactmethod/contactmethod.go
  user/contactmethod/store.go
  user/notificationrule/notificationrule.go
  user/notificationrule/notificationrule_test.go
Labels: size/l

#3981 dest: move desttypes to nfydest package
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graphqlapp/destinationtypes.go
  graphql2/models_gen.go
  notification/nfydest/provider.go
  notification/nfydest/registry.go
  notification/nfydest/typeinfo.go
Labels: size/l

#3982 dest: use single "registry" for slack channel destination type
  app/app.go
  app/initgraphql.go
  app/initstores.go
  app/startup.go
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  graphql2/models_gen.go
  notification/nfydest/provider.go
  notification/nfydest/registry.go
  notification/nfydest/search.go
  notification/slack/nfydest.go
  notification/slack/nfydestchannel.go
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/l

#3983 dest: move slack DM to `nfydest.Registry`
  app/startup.go
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  notification/nfydest/provider.go
  notification/nfydest/registry.go
  notification/nfydest/validate.go
  notification/slack/nfydestchannel.go
  notification/slack/nfydestdm.go
Labels: size/l

#3992 nfydest: move slack usergroup support to registry
  app/startup.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  notification/slack/nfydestug.go
Labels: size/m

#3993 nfydest: move webhook to `nfydest.Registry`
  app/startup.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  notification/webhook/nfydest.go
Labels: size/m

#3995 dest: Validate actions and add alert destination to registry
  alert/nfydest.go
  app/initstores.go
  app/startup.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  integrationkey/config.go
  integrationkey/store.go
  integrationkey/uik/compilerule.go
  notification/nfydest/registry.go
  notification/nfydest/validate.go
  notification/nfydest/validateaction.go
Labels: size/l

#3994 ui: combine create and edit uik dialogs
  web/src/app/services/UniversalKey/UniversalKeyRuleConfig.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleCreateDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleDialog.tsx
Labels: size/s

#3996 dest: move user to nfydest.Registry
  app/startup.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  notification/nfydest/search.go
  notification/slack/channel.go
  notification/slack/nfydestchannel.go
  notification/slack/nfydestug.go
  notification/slack/usergroup.go
  user/nfydest.go
  user/search.go
Labels: size/l

#3947 ui: universal integration keys
  test/integration/uik.spec.ts
  web/src/app/dialogs/FormDialog.jsx
  web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyActionsForm.tsx
  web/src/app/services/UniversalKey/UniversalKeyActionsList.tsx
  web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleForm.tsx
  web/src/app/services/UniversalKey/utils.tsx
Labels: size/l

#3998 dest: move schedule and rotation to `nfydest.Registry`
  app/startup.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  schedule/nfydest.go
  schedule/rotation/nfydest.go
Labels: size/l

#3999 ep: use dest/actions instead of targets
  app/initstores.go
  escalation/desttargets.go
  escalation/queries.sql
  escalation/store.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graph/escalationpolicy.graphqls
  graphql2/graphqlapp/escalationpolicy.go
  graphql2/schema.graphql
  notification/nfydest/registry.go
  notificationchannel/queries.sql
  notificationchannel/store.go
  schedule/nfydest.go
  schedule/rotation/nfydest.go
  sqlc.yaml
  user/nfydest.go
Labels: size/l

#4000 ui: add tooltip to formdialog action buttons, use for universal keys
  web/src/app/alerts/CreateAlertDialog/CreateAlertDialog.tsx
  web/src/app/dialogs/FormDialog.jsx
  web/src/app/services/UniversalKey/UniversalKeyActionsForm.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleForm.tsx
Labels: size/m

#4001 dest: bugfix on error paths
  graphql2/graphqlapp/destinationvalidation.go
  notification/slack/channel.go
Labels: size/xs

#4002 dest: move remaining EP code away from targets and to dest
  devtools/resetdb/datagen.go
  devtools/resetdb/main.go
  escalation/desttargets.go
  escalation/step.go
  escalation/store.go
  graphql2/generated.go
  graphql2/graph/escalationpolicy.graphqls
  graphql2/graphqlapp/escalationpolicy.go
  graphql2/graphqlapp/target.go
  graphql2/schema.graphql
  util/errutil/maperror.go
Labels: size/l

#4003 escalation: Remove unused step target methods
  escalation/store.go
Labels: size/l

#4004 Transition OnCallNotificatonRule to use 'Dest' field
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/escalationpolicy.go
  graphql2/graphqlapp/messagelog.go
  graphql2/graphqlapp/mutation.go
  graphql2/graphqlapp/schedule.go
  graphql2/graphqlapp/target.go
  graphql2/inputs.go
  graphql2/schema.graphql
  notificationchannel/queries.sql
  notificationchannel/store.go
  schedule/oncallnotificationrule.go
Labels: size/l

#4005 dest: migrate remaining contact method destinations to the `nfydest.Registry`
  .github/workflows/main.yml
  .storybook/static/mockServiceWorker.js
  .yarnrc.yml
  app/startup.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  notification/email/nfydest.go
  notification/twilio/nfydestsms.go
  notification/twilio/nfydestvoice.go
  package.json
  web/src/app/util/DestinationInputChip.stories.tsx
  yarn.lock
Labels: size/l

#4013 dest: switch UI and alertlog from type/val to dest
  alert/alertlog/queries.sql
  alert/alertlog/store.go
  app/initstores.go
  engine/backend.go
  escalation/store.go
  gadb/queries.sql.go
  graphql2/graphqlapp/alert.go
  graphql2/graphqlapp/queries.sql
  integrationkey/config.go
  integrationkey/queries.sql
  integrationkey/store.go
  migrate/migrations/20240726113949-fix-dest-update-trg.sql
  migrate/schema.sql
  notification/nfydest/registry.go
  notificationchannel/store.go
  web/src/app/admin/admin-service-metrics/AdminServiceMetrics.tsx
  web/src/app/admin/admin-service-metrics/AdminServiceTable.tsx
  web/src/app/admin/admin-service-metrics/useServiceMetrics.ts
  web/src/app/admin/admin-service-metrics/useServices.ts
  web/src/app/alerts/components/AlertDetails.tsx
  web/src/app/alerts/pages/AlertDetailPage.tsx
  web/src/app/escalation-policies/PolicyStepsQuery.tsx
  web/src/app/services/ServiceOnCallList.tsx
Labels: size/l

#4012 notification: move message status lookups to sqlc
  engine/message/db.go
  engine/sendmessage.go
  gadb/models.go
  gadb/providermessageid.go
  gadb/queries.sql.go
  graphql2/graphqlapp/messagelog.go
  graphql2/graphqlapp/toolbox.go
  notification/destcompat.go
  notification/manager.go
  notification/messagetype.go
  notification/messagetype_string.go
  notification/queries.sql
  notification/search.go
  notification/status.go
  notification/store.go
  notification/webhook/sender.go
  sqlc.yaml
  web/src/cypress/e2e/admin.cy.ts
Labels: size/l

#4019 ui: fix edit empy temp sched bug
  web/src/app/schedules/ScheduleOverrideDialog.jsx
  web/src/app/schedules/temp-sched/TempSchedDialog.tsx
  web/src/app/util/FilterContainer.jsx
Labels: size/s

#4020 dest: move to DestV1 away from DestType
  engine/engine.go
  engine/isknowndest.go
  engine/message/bundlealerts.go
  engine/message/db.go
  engine/message/dedupalerts.go
  engine/message/deduponcallnotifications.go
  engine/message/dedupstatusmessages.go
  engine/message/queue.go
  engine/message/queue_test.go
  engine/sendmessage.go
  gadb/dest.go
  gadb/queries.sql.go
  graphql2/graphqlapp/messagelog.go
  notification/desttype.go
  notification/namedreceiver.go
  notification/receiver.go
  notification/resultreceiver.go
  notification/store.go
  notification/twilio/sms.go
  notification/twilio/voice.go
  user/contactmethod/queries.sql
  user/contactmethod/store.go
Labels: size/l

#4021 dest: use DestV1 in notification.Message
  app/initgraphql.go
  app/initslack.go
  app/inittwilio.go
  app/startup.go
  engine/message/db.go
  engine/message/queries.sql
  engine/message/queue.go
  engine/message/queue_test.go
  engine/message/ratelimit.go
  engine/message/ratelimit_test.go
  engine/message/throttle.go
  engine/message/throttleconfigbuilder.go
  engine/message/throttleconfigbuilder_test.go
  engine/sendmessage.go
  gadb/queries.sql.go
  graphql2/graphqlapp/alert.go
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/messagelog.go
  graphql2/graphqlapp/toolbox.go
  notification/alert.go
  notification/alertbundle.go
  notification/alertstatus.go
  notification/destcompat.go
  notification/desttype.go
  notification/email/sender.go
  notification/manager.go
  notification/message.go
  notification/namedreceiver.go
  notification/namedsender.go
  notification/scheduleoncallusers.go
  notification/signal.go
  notification/slack/channel.go
  notification/slack/usergroupsender.go
  notification/status.go
  notification/store.go
  notification/testnotification.go
  notification/twilio/client_test.go
  notification/twilio/sms.go
  notification/twilio/voice.go
  notification/twilio/voice_test.go
  notification/verification.go
  notification/webhook/sender.go
  test/smoke/harness/backend.go
Labels: size/l

#4022 notification: remove DestType and Dest
  devtools/resetdb/datagen.go
  engine/message/bundlealerts.go
  engine/message/db.go
  engine/message/dedupalerts.go
  engine/message/dedupalerts_test.go
  engine/message/deduponcallnotifications.go
  engine/message/dedupstatusmessages.go
  engine/message/message.go
  engine/message/queue.go
  engine/message/queue_test.go
  engine/message/ratelimit_test.go
  engine/message/throttle.go
  engine/message/throttleconfigbuilder_test.go
  engine/sendmessage.go
  gadb/dest.go
  notification/alert.go
  notification/destid.go
  notification/desttype.go
  notification/desttype_string.go
  notification/twilio/client_test.go
Labels: size/m
