Repository target/goalert, pull requests merged in 2024-12, with the labels that each got.

#4166 deps: update Go deps
  go.mod
  go.sum
  golangci-lint.version
  graphql2/graphqlapp/app.go
  mailpit.version
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
  protoc.version
Labels: size/xs

#4165 build: refactor container build process to use docker buildx
  Makefile.binaries.mk
  devtools/ci/dockerfiles/demo/Dockerfile.prebuilt
  devtools/ci/dockerfiles/goalert/Dockerfile.prebuilt
  devtools/genmake/template.mk
Labels: size/s

#4173 engine: add support for triggering all periodic jobs during tests
  app/initriver.go
  app/startup.go
  devtools/procwrap/main.go
  engine/engine.go
  engine/jobtrigger.go
  engine/processinglock/module.go
  engine/signalmgr/setup.go
  test/smoke/harness/backend.go
  web/src/cypress/e2e/admin.cy.ts
  web/src/cypress/e2e/services.cy.ts
  web/src/cypress/plugins/index.js
  web/src/cypress/support/sql.ts
  web/src/cypress/support/util.ts
  web/src/cypress/tsconfig.json
Labels: size/l

#4174 readme: update development setup guide
  README.md
  docs/development-setup.md
  docs/getting-started.md
Labels: size/m

#4103 heartbeat: allow muting a heartbeat monitor
  engine/heartbeatmanager/db.go
  engine/heartbeatmanager/process.go
  gadb/models.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  heartbeat/monitor.go
  heartbeat/queries.sql
  heartbeat/store.go
  migrate/migrations/20241126103529-hb-monitor-disable.sql
  migrate/schema.sql
  sqlc.yaml
  test/smoke/heartbeat_test.go
  util/sqlutil/interval.go
  web/src/app/services/HeartbeatMonitorForm.tsx
  web/src/schema.d.ts
Labels: size/l, DB Migration

#4185 event: add event bus to replace manual trigger of periodic jobs
  Makefile
  app/app.go
  app/initengine.go
  app/initriver.go
  app/initstores.go
  app/shutdown.go
  engine/config.go
  engine/engine.go
  engine/jobtrigger.go
  engine/processinglock/module.go
  engine/signalmgr/setup.go
  event/bus.go
  event/bus_test.go
  go.mod
  integrationkey/uik/handler.go
  test/smoke/harness/twilioassertionapi.go
  web/src/cypress/support/sql.ts
Labels: size/l

#4164 engine: migrate status update manager to job queue
  alert/store.go
  app/initstores.go
  engine/engine.go
  engine/signalmgr/triggerservice.go
  engine/statusmgr/cleanup.go
  engine/statusmgr/db.go
  engine/statusmgr/lookforwork.go
  engine/statusmgr/process.go
  engine/statusmgr/queries.sql
  engine/statusmgr/setup.go
  engine/statusmgr/update.go
  gadb/queries.sql.go
Labels: size/l

#4186 engine/cleanupmanager: move alert cleanup to job queue and sqlc
  app/initriver.go
  engine/cleanupmanager/alerts.go
  engine/cleanupmanager/db.go
  engine/cleanupmanager/queries.sql
  engine/cleanupmanager/setup.go
  engine/cleanupmanager/update.go
  engine/engine.go
  engine/processinglock/module.go
  gadb/queries.sql.go
  test/smoke/alertautoclose_test.go
  test/smoke/alertcleanup_test.go
  test/smoke/harness/harness.go
  util/contextsleep.go
Labels: size/l

#4189 uik: add some clarity to using universal keys
  web/src/app/services/IntegrationKeyList.tsx
  web/src/app/services/UniversalKey/UniversalKeyPage.tsx
Labels: size/s

#4194 adding info link to expr syntax
  web/src/app/services/UniversalKey/ExprField.tsx
Labels: size/xs

#4193 uik: Single dialog for default actions
  web/src/app/dialogs/FormDialog.jsx
  web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyActionDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyActionsList.tsx
  web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
  web/src/app/util/DestinationChip.tsx
  web/src/app/util/DestinationInputChip.tsx
  web/src/app/util/RequireConfig.tsx
Labels: size/l

#4192 engine/cleanupmgr: Migrate shifts to job queue
  engine/cleanupmanager/db.go
  engine/cleanupmanager/queries.sql
  engine/cleanupmanager/shifts.go
  engine/cleanupmanager/update.go
  gadb/queries.sql.go
Labels: size/m

#4203 engine/cleanupmgr: move schedule data cleanup to job queue
  app/initengine.go
  engine/cleanupmanager/alerts.go
  engine/cleanupmanager/db.go
  engine/cleanupmanager/queries.sql
  engine/cleanupmanager/scheddata.go
  engine/cleanupmanager/setup.go
  engine/cleanupmanager/update.go
  engine/config.go
  engine/engine.go
  gadb/queries.sql.go
Labels: size/l

#4205 chore(deps): add group for Go dependencies in dependabot configuration
  .github/dependabot.yml
Labels: size/xs

#4209 engine/cleanupmgr: individualize schedule data cleanup jobs
  engine/cleanupmanager/queries.sql
  engine/cleanupmanager/scheddata.go
  engine/cleanupmanager/setup.go
  gadb/queries.sql.go
Labels: size/m

#4196 calsub: Add JSON as a supported format for calendar subscriptions
  calsub/http.go
  test/smoke/calendarsubscriptionjson_test.go
Labels: size/m

#4211 engine/cleanupmgr: move alert log operations to job queue
  app/initriver.go
  engine/cleanupmanager/alertlogs.go
  engine/cleanupmanager/db.go
  engine/cleanupmanager/queries.sql
  engine/cleanupmanager/setup.go
  engine/cleanupmanager/update.go
  gadb/queries.sql.go
Labels: size/m

#4219 Add tooltip for on-call notification clarity
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
Labels: size/xs

#4218 engine/cleanupmgr: finalize migration to job queue for cleanup operations
  engine/cleanupmanager/apikeys.go
  engine/cleanupmanager/db.go
  engine/cleanupmanager/queries.sql
  engine/cleanupmanager/setup.go
  engine/cleanupmanager/update.go
  gadb/queries.sql.go
Labels: size/m

#4104 engine/compatmanager: migrate to sqlc
  engine/compatmanager/db.go
  engine/compatmanager/queries.sql
  engine/compatmanager/update.go
  gadb/queries.sql.go
Labels: size/m
