Repository target/goalert, pull requests merged in 2024-03, with the labels that each got.

#3743 dev: CST/CDT changes, use testid
  test/integration/schedules.spec.ts
  web/src/app/schedules/ScheduleShiftList.tsx
Labels: size/xs

#3717 dest/escalation-policies: use destinations for EP step form
  graphql2/graphqlapp/destinationdisplayinfo.go
  web/src/app/escalation-policies/PolicyStepFormDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepFormDest.tsx
  web/src/app/selection/DestinationInputDirect.tsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/users/UserContactMethodCreateDialogDest.stories.tsx
  web/src/app/util/RequireConfig.tsx
Labels: size/l

#3741 sched/notif: retain time and weekday filter if swapping radio options
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsFormDest.tsx
Labels: size/s

#3744 graphql: Convert empty UUID strings to NullUUID
  alert/alertlog/store.go
  apikey/store.go
  auth/handler.go
  escalation/store.go
  permission/context.go
  schedule/rotation/store.go
  schedule/store.go
  service/store.go
  test/integration/gqlapikeys.spec.ts
  test/smoke/gqlapikeys_test.go
  test/smoke/harness/graphql.go
  user/store.go
Labels: size/m

#3745 chore: update go.sum
  go.sum
Labels: size/xs

#3734 dev: update demo container for integration test usage
  README.md
  devtools/ci/dockerfiles/demo/start.sh
Labels: size/s

#3719 dest: add dest version of schedule notification edit dialog
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialogDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialogDest.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.tsx
Labels: size/l

#3718 dest/escalation-policies: use destinations for EP step create dialog
  playwright.config.ts
  test/integration/escalation-policies.spec.ts
  test/integration/setup/global-teardown.ts
  web/src/app/escalation-policies/PolicyStepCreateDialogDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepCreateDialogDest.tsx
  web/src/app/escalation-policies/PolicyStepFormDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepFormDest.tsx
  web/src/app/escalation-policies/PolicyStepsCard.jsx
  web/src/app/forms/FormField.jsx
  web/src/app/selection/DestinationSearchSelect.tsx
Labels: size/l

#3760 dev: update protoc to latest version
  go.mod
  go.sum
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
  protoc.version
Labels: size/xs

#3746 dev: update to storybook 8
  .storybook/preview.ts
  package.json
  web/src/app/escalation-policies/PolicyStepFormDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialogDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsFormDest.stories.tsx
  web/src/app/users/UserContactMethodCreateDialogDest.stories.tsx
  yarn.lock
Labels: size/s

#3763 intkeys: fix site24x7 label bug
  graphql2/graphqlapp/config.go
  web/src/app/escalation-policies/PolicyStepCreateDialogDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialogDest.stories.tsx
Labels: size/xs

#3720 user contact method edit dialog dest
  graphql2/graphqlapp/contactmethod.go
  web/src/app/escalation-policies/PolicyStepCreateDialogDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialogDest.stories.tsx
  web/src/app/users/UserContactMethodEditDialog.tsx
  web/src/app/users/UserContactMethodEditDialogDest.stories.tsx
  web/src/app/users/UserContactMethodEditDialogDest.tsx
  web/src/app/users/UserContactMethodListDest.tsx
Labels: size/l

#3770 devtools/pgdump-lite: use pool for pgdump-lite, csv output for COPY
  devtools/pgdump-lite/cmd/pgdump-lite/main.go
  devtools/pgdump-lite/dumpdata.go
  devtools/pgdump-lite/dumpschema.go
  devtools/pgdump-lite/pgd/db.go
  devtools/pgdump-lite/pgd/models.go
  devtools/pgdump-lite/pgd/queries.sql.go
Labels: size/l

#3776 graphql: use tx with create alert
  alert/store.go
  graphql2/graphqlapp/alert.go
Labels: size/s

#3777 graphql: remove experimental directive for dest-types
  graphql2/generated.go
  graphql2/graph/destinations.graphqls
  graphql2/graph/escalationpolicy.graphqls
  graphql2/schema.graphql
Labels: size/s

#3775 util/sqlutil: fix handling of block delimiters in SplitQuery
  util/sqlutil/splitquery.go
  util/sqlutil/splitquery_test.go
Labels: size/s
