Repository target/goalert, pull requests merged in 2024-05, with the labels that each got.

#3825 urql: move service list to urql
  web/src/app/services/ServiceCreateDialog.tsx
  web/src/app/services/ServiceList.tsx
  web/src/app/users/UserList.tsx
Labels: size/m

#3826 urql: move policy list to urql
  web/src/app/escalation-policies/PolicyList.tsx
Labels: size/s

#3827 urql: move schedule list to urql
  web/src/app/schedules/ScheduleList.tsx
Labels: size/s

#3828 urql: move rotation list to urql
  web/src/app/rotations/RotationList.tsx
Labels: size/s

#3836 add type universal to integration keys
  alert/alert.go
  alert/alertlog/legacylogs.go
  alert/source.go
  gadb/models.go
  go.mod
  graphql2/graphqlapp/config.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  integrationkey/store.go
  integrationkey/type.go
  migrate/migrations/20240502114803-universal-integration-key.sql
  migrate/schema.sql
  web/src/schema.d.ts
Labels: size/s

#3837 intkey: update old code to use API-driven key types
  web/src/app/admin/admin-service-metrics/AdminServiceFilter.tsx
  web/src/app/wizard/WizardForm.jsx
Labels: size/s

#3847 uik: add basic CRUD operations
  gadb/models.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graph/univkeys.graphqls
  graphql2/graphqlapp/integrationkey.go
  graphql2/models_gen.go
  integrationkey/config.go
  integrationkey/queries.sql
  migrate/migrations/20240503155449-uik-config.sql
  migrate/schema.sql
  web/src/schema.d.ts
Labels: size/l

#3849 expr: use scalar GraphQL types to handle validation
  graphql2/exprscalar.go
  graphql2/exprscalar_test.go
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graph/expr.graphqls
  graphql2/graph/univkeys.graphqls
  graphql2/graphqlapp/expr.go
  graphql2/graphqlapp/expr_test.go
  graphql2/models_gen.go
  web/src/schema.d.ts
Labels: size/l

#3848 ui: update breadcrumbs to handle doubly nested routes
  web/src/app/main/components/BreadCrumb.tsx
  web/src/app/main/components/ToolbarPageTitle.tsx
  web/src/app/util/AppLink.tsx
Labels: size/l

#3850 ui/list: padding and console fixes
  web/src/app/lists/FlatList.tsx
  web/src/app/lists/FlatListItem.tsx
  web/src/app/services/IntegrationKeyList.tsx
  web/src/app/util/AppLink.tsx
Labels: size/s

#3855 list pages: fix conditional create button rendering
  web/src/app/lists/ListPageControls.tsx
Labels: size/xs

#3856 urql: PolicyCreateDialog and UserContactMethodEditDialog
  web/src/app/escalation-policies/PolicyCreateDialog.tsx
  web/src/app/users/UserContactMethodEditDialog.tsx
Labels: size/s

#3785 ui/sched: always use Dest API
  web/src/app/main/AppRoutes.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialogDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialogDest.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialogDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialogDest.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.stories.tsx
  web/src/cypress/e2e/schedules.cy.ts
Labels: size/m

#3851 uik: add bounds/limits on int key config
  integrationkey/config.go
  validation/validate/range.go
Labels: size/s

#3874 ui: update material select tests
  web/src/cypress/e2e/escalationPolicies.cy.ts
  web/src/cypress/e2e/materialSelect.cy.ts
Labels: size/m

#3876 ui/profile: add helpers and move notification rule tests to playwright
  test/integration/email-cm.spec.ts
  test/integration/lib/index.ts
  test/integration/lib/select.ts
  web/src/cypress/e2e/profile.cy.ts
Labels: size/m

#3871 profile: optimize on-call query
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graphqlapp/queries.sql
  graphql2/graphqlapp/user.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserOnCallAssignmentList.tsx
  web/src/schema.d.ts
Labels: size/m

#3867 ui/policy: always use Dest API
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertConfirm.tsx
  web/src/app/alerts/CreateAlertDialog/StepContent/CreateAlertServiceSelect.tsx
  web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
  web/src/app/escalation-policies/PolicyStepEditDialog.tsx
  web/src/app/escalation-policies/PolicyStepEditDialogDest.tsx
  web/src/app/escalation-policies/PolicyStepForm.jsx
  web/src/app/escalation-policies/PolicyStepFormDest.tsx
  web/src/app/escalation-policies/PolicyStepsCard.tsx
  web/src/app/escalation-policies/PolicyStepsQuery.tsx
  web/src/app/escalation-policies/stepUtil.tsx
  web/src/app/selection/ChanWebhookSelect.tsx
  web/src/app/selection/index.js
  web/src/app/util/Chips.tsx
  web/src/app/util/ServiceChip.tsx
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
  web/src/cypress/e2e/favorites.cy.ts
Labels: size/l

#3875 ui/profile: always use Dest API
  graphql2/generated.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationvalidation.go
  graphql2/schema.graphql
  test/integration/email-cm.spec.ts
  test/integration/first-login.spec.ts
  test/integration/setup/goalert-config.json
  web/src/app/main/components/NewUserSetup.tsx
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/users/UserContactMethodEditDialog.tsx
  web/src/app/users/UserContactMethodForm.tsx
  web/src/app/users/UserContactMethodList.tsx
  web/src/app/users/UserContactMethodListDest.tsx
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserNotificationRuleCreateDialog.tsx
  web/src/app/users/UserNotificationRuleList.tsx
  web/src/cypress/e2e/profile.cy.ts
Labels: size/l

#3878 ui: update escalation policy step button text
  test/integration/escalation-policies.spec.ts
  web/src/app/escalation-policies/PolicyStepCreateDialogDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepEditDialogDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepFormDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepFormDest.tsx
  web/src/cypress/e2e/escalationPolicySteps.cy.ts
Labels: size/s

#3877 uik: add deleteSecondaryToken mutation
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graph/univkeys.graphqls
  graphql2/graphqlapp/integrationkey.go
  integrationkey/queries.sql
  integrationkey/uik.go
  web/src/schema.d.ts
Labels: size/s

#3880 uik: add methods of updating single rules
  graphql2/generated.go
  graphql2/graph/univkeys.graphqls
  graphql2/graphqlapp/integrationkey.go
  graphql2/models_gen.go
  web/src/schema.d.ts
Labels: size/s

#3879 uik: implement new endpoint and authorization
  app/inithttp.go
  auth/handler.go
  gadb/queries.sql.go
  graphql2/graphqlapp/integrationkey.go
  integrationkey/config.go
  integrationkey/queries.sql
  integrationkey/uik.go
  permission/source.go
  permission/sourcetype_string.go
Labels: size/m

#3882 playwright: fix flaky contact method tests
  test/integration/email-cm.spec.ts
  test/integration/first-login.spec.ts
  test/integration/lib/select.ts
  web/src/app/lists/FlatList.tsx
  web/src/app/lists/FlatListItem.tsx
  web/src/app/users/UserContactMethodDeleteDialog.tsx
  web/src/app/users/UserNotificationRuleDeleteDialog.tsx
  web/src/app/util/OtherActionsDesktop.jsx
  web/src/app/util/SpeedDial.tsx
Labels: size/s

#3881 expflag: remove dest-types flag
  expflag/flags.go
  test/integration/escalation-policies.spec.ts
  web/src/app/escalation-policies/PolicyStepCreateDialogDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepEditDialogDest.stories.tsx
  web/src/app/escalation-policies/PolicyStepFormDest.stories.tsx
  web/src/app/selection/DestinationInputDirect.stories.tsx
  web/src/app/selection/DestinationSearchSelect.stories.tsx
  web/src/app/users/UserContactMethodCreateDialogDest.stories.tsx
  web/src/app/users/UserContactMethodEditDialogDest.stories.tsx
  web/src/app/users/UserContactMethodFormDest.stories.tsx
  web/src/app/users/UserContactMethodListDest.stories.tsx
  web/src/app/users/UserNotificationRuleListDest.stories.tsx
  web/src/app/util/DestinationInputChip.stories.tsx
  web/src/app/util/TelTextField.stories.tsx
  web/src/expflag.d.ts
Labels: size/s

#3894 uik: add token rotation dialogs and controls
  test/integration/lib/integration-key.ts
  test/integration/lib/label.ts
  test/integration/lib/select.ts
  test/integration/lib/service.ts
  test/integration/uik.spec.ts
  web/src/app/details/CardActions.tsx
  web/src/app/dialogs/FormDialog.jsx
  web/src/app/services/UniversalKey/DeleteSecondaryTokenDialog.tsx
  web/src/app/services/UniversalKey/GenTokenDialog.tsx
  web/src/app/services/UniversalKey/PromoteTokenDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyPage.tsx
Labels: size/l

#3898 uik: add dynamic actions api
  app/app.go
  app/inithttp.go
  app/initstores.go
  graphql2/generated.go
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/destinationtypes.go
  graphql2/models_gen.go
  integrationkey/uik.go
  integrationkey/uik/handler.go
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/util/RequireConfig.tsx
  web/src/schema.d.ts
Labels: size/l

#3899 storybook: allow for per-story graphql mocking
  .storybook/preview.ts
  web/src/app/storybook/decorators.tsx
  web/src/app/urql.ts
  web/src/app/util/TelTextField.stories.tsx
Labels: size/m

#3909 ui: add DynamicActionField component
  web/src/app/selection/DestinationField.tsx
  web/src/app/selection/DynamicActionForm.stories.tsx
  web/src/app/selection/DynamicActionForm.tsx
Labels: size/l
