Repository target/goalert, pull requests merged in 2024-06, with the labels that each got.

#3895 ui/chore: remove "Dest" suffix from relevant UI files
  web/src/app/escalation-policies/PolicyStepCreateDialog.stories.tsx
  web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
  web/src/app/escalation-policies/PolicyStepDeleteDialog.tsx
  web/src/app/escalation-policies/PolicyStepEditDialog.stories.tsx
  web/src/app/escalation-policies/PolicyStepEditDialog.tsx
  web/src/app/escalation-policies/PolicyStepForm.stories.tsx
  web/src/app/escalation-policies/PolicyStepForm.tsx
  web/src/app/escalation-policies/PolicyStepsCard.tsx
  web/src/app/main/AppRoutes.tsx
  web/src/app/main/components/NewUserSetup.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
  web/src/app/users/UserContactMethodCreateDialog.stories.tsx
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/users/UserContactMethodEditDialog.stories.tsx
  web/src/app/users/UserContactMethodEditDialog.tsx
  web/src/app/users/UserContactMethodForm.stories.tsx
  web/src/app/users/UserContactMethodForm.tsx
  web/src/app/users/UserContactMethodList.stories.tsx
  web/src/app/users/UserContactMethodList.tsx
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserNotificationRuleList.tsx
  web/src/app/users/UserNotificationRuleListDest.stories.tsx
Labels: size/m

#3916 ui: fix step number display for EP step delay text
  test/integration/escalation-policies.spec.ts
  web/src/app/escalation-policies/stepUtil.tsx
Labels: size/s

#3926 dest/action: simplify error flow in forms
  web/src/app/forms/HelperText.tsx
  web/src/app/forms/index.js
  web/src/app/selection/DestinationField.tsx
  web/src/app/selection/DestinationInputDirect.tsx
  web/src/app/selection/DestinationSearchSelect.tsx
  web/src/app/selection/DynamicActionForm.stories.tsx
  web/src/app/selection/DynamicActionForm.tsx
Labels: size/m

#3938 graphql: add StringMap for destinations
  devtools/gqltsgen/run.go
  graphql2/compatdestinput.go
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graph/destinations.graphqls
  graphql2/graph/errorcodes.graphqls
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/destinationvalidation.go
  graphql2/models_gen.go
  graphql2/stringmap.go
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/selection/DynamicActionForm.tsx
  web/src/app/users/UserContactMethodEditDialog.stories.tsx
  web/src/app/users/UserContactMethodList.stories.tsx
  web/src/app/util/errtypes.ts
  web/src/schema.d.ts
Labels: size/l

#3939 Add ErrorConsumer
  web/src/app/util/ErrorConsumer.ts
Labels: size/m

#3940 DestinationField StringMap update
  graphql2/stringmap.go
  web/src/app/escalation-policies/PolicyStepCreateDialog.stories.tsx
  web/src/app/escalation-policies/PolicyStepCreateDialog.tsx
  web/src/app/escalation-policies/PolicyStepEditDialog.stories.tsx
  web/src/app/escalation-policies/PolicyStepEditDialog.tsx
  web/src/app/escalation-policies/PolicyStepForm.stories.tsx
  web/src/app/escalation-policies/PolicyStepForm.tsx
  web/src/app/loading/components/LoadingButton.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsForm.tsx
  web/src/app/selection/DestinationField.stories.tsx
  web/src/app/selection/DestinationField.tsx
  web/src/app/selection/DestinationInputDirect.tsx
  web/src/app/selection/DynamicActionForm.tsx
  web/src/app/users/UserContactMethodForm.tsx
  web/src/app/util/DestinationInputChip.stories.tsx
Labels: size/l

#3941 gqlapi: Ensure stable hash for API key policy
  apikey/policy.go
  apikey/policyinfo.go
  apikey/policyinfo_test.go
Labels: size/s

#3943 dest: update user forms to use StringMap instead of FieldValuePair[]
  web/src/app/forms/HelperText.tsx
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/users/UserContactMethodEditDialog.stories.tsx
  web/src/app/users/UserContactMethodEditDialog.tsx
  web/src/app/users/UserContactMethodForm.stories.tsx
  web/src/app/users/UserContactMethodForm.tsx
  web/src/app/users/UserContactMethodList.stories.tsx
  web/src/app/users/UserContactMethodList.tsx
Labels: size/m

#3944 Update DynamicParams to use ExprStringMap
  graphql2/exprscalar.go
  graphql2/generated.go
  graphql2/gqlgen.yml
  graphql2/graph/univkeys.graphqls
  graphql2/graphqlapp/integrationkey.go
  graphql2/models_gen.go
  test/smoke/actionvalidate_test.go
  test/smoke/harness/graphql.go
  web/src/app/forms/HelperText.tsx
  web/src/app/selection/DynamicActionForm.tsx
  web/src/schema.d.ts
Labels: size/m

#3945 Add Universal Key Actions management forms
  web/src/app/selection/DynamicActionForm.tsx
  web/src/app/services/UniversalKey/UniversalKeyActionsForm.tsx
  web/src/app/services/UniversalKey/UniversalKeyActionsList.tsx
  web/src/app/services/UniversalKey/UniversalKeysActionsForm.stories.tsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/util/DestinationAvatar.tsx
  web/src/app/util/DestinationChip.tsx
  web/src/app/util/DestinationInputChip.tsx
Labels: size/l

#3946 Add default action edit and rule management dialogs
  web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleForm.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleRemoveDialog.tsx
  web/src/app/services/UniversalKey/utils.tsx
Labels: size/l
