Repository target/goalert, pull requests merged in 2024-10, with the labels that each got.

#4025 Add documentation for Universal Integration Keys
  docs/universal-integration-keys.md
Labels: size/s

#4073 integrationkey/uik: Wrap error in validation for HTTP response
  integrationkey/uik/handler.go
Labels: size/xs

#4090 fix: fix slice init length
  alert/store.go
Labels: size/xs

#4091 test/smoke/harness: migrate from MailHog to Mailpit
  Makefile
  Procfile
  Procfile.prod
  Procfile.swo
  devtools/gettool/getmailpit.go
  devtools/gettool/run.go
  devtools/tools.go
  go.mod
  go.sum
  mailpit.version
  pkg/sysapi/sysapi.pb.go
  playwright.config.ts
  test/integration/email-cm.spec.ts
  test/smoke/harness/email.go
  test/smoke/harness/email_test.go
  test/smoke/harness/mailpit.go
  test/smoke/harness/mailpit_test.go
  web/src/app/public/logos/goalert-alt-logo.png
Labels: size/l
