Repository target/goalert, pull requests merged in 2024-11, with the labels that each got.

#4115 add smtp retries
  remotemonitor/config.go
  remotemonitor/monitor.go
Labels: size/s

#4116 engine/schedulemanager: convert to sqlc
  engine/schedulemanager/db.go
  engine/schedulemanager/queries.sql
  engine/schedulemanager/update.go
  gadb/models.go
  gadb/queries.sql.go
  schedule/data.go
  sqlc.yaml
Labels: size/l

#4106 engine/processinglock: migrate to sqlc
  calsub/queries.sql
  engine/processinglock/config.go
  engine/processinglock/lock.go
  engine/processinglock/queries.sql
  engine/processinglock/state.go
  gadb/models.go
  gadb/queries.sql.go
  sqlc.yaml
Labels: size/m

#4123 util/timeutil: Ensure exponents are never encoded into the output String()
  util/timeutil/isoduration.go
  util/timeutil/isoduration_test.go
Labels: size/xs

#4124 logging: introduce slog.Logger
  app/app.go
  app/cmd.go
  app/config.go
  app/context.go
  app/initsmtpsrv.go
  app/initstores.go
  app/listenevents.go
  app/multilistener.go
  app/multilistener_test.go
  app/pause.go
  app/runapp.go
  app/startup.go
  go.mod
  go.sum
  smtpsrv/config.go
  smtpsrv/server.go
  test/smoke/harness/harness.go
  util/log/log.go
Labels: size/m

#4125 db: use pgxpool.Pool for database connections
  app/app.go
  app/cmd.go
  app/shutdown.go
  gadb/queries.sql.go
  retry/wrap.go
  sqlc.yaml
  swo/connector.go
  swo/manager.go
  swo/pgxpool.go
  swo/queries.sql
  swo/swodb/queries.sql.go
  test/smoke/harness/harness.go
  util/sqldrv/appurl.go
  util/sqldrv/connector.go
  util/sqldrv/retryconnector.go
  util/sqldrv/retrydriver.go
  util/sqldrv/retrylookup.go
Labels: size/m

#4126 migrate: Use SplitQuery for migration parsing
  devtools/pgdump-lite/pgd/db.go
  devtools/pgdump-lite/pgd/models.go
  devtools/pgdump-lite/pgd/queries.sql.go
  go.mod
  go.sum
  migrate/migrate.go
  migrate/migrations/20170712094434-notification-policy-updates.sql
  migrate/schema.sql
Labels: size/s

#4137 pgxpool: Don't use idle connections with stdlib when doing pooling
  app/app.go
  app/cmd.go
  app/pause.go
  migrate/migrate.go
  swo/manager.go
  swo/pgxpool.go
Labels: size/s

#4136 go: update Go to 1.23.3 and dependencies
  devtools/ci/dockerfiles/build-env/Dockerfile
  devtools/ci/dockerfiles/goalert/Dockerfile
  devtools/ci/tasks/build-all.yml
  devtools/ci/tasks/build-binaries.yml
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/ci/tasks/test-smoketest.yml
  go.mod
  go.sum
  golangci-lint.version
  graphql2/generated.go
  mailpit.version
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
  protoc.version
Labels: size/xs

#4135 engine: river job queue
  app/app.go
  app/initengine.go
  app/inithttp.go
  app/initriver.go
  app/runapp.go
  app/startup.go
  devtools/scripts/gen-river-migration.sh
  devtools/scripts/validate-migrations.sh
  devtools/tools.go
  engine/config.go
  engine/engine.go
  gadb/models.go
  go.mod
  go.sum
  migrate/migrations/20241108160105-import-river-migration-2.sql
  migrate/migrations/20241108160105-import-river-migration-3.sql
  migrate/migrations/20241108160105-import-river-migration-4.sql
  migrate/migrations/20241108160105-import-river-migration-5.sql
  migrate/migrations/20241108160106-import-river-migration-6.sql
  migrate/migrations/20241108165850-river-queue-add-ids.sql
  migrate/schema.sql
  web/src/app/main/NavBar.tsx
  web/src/app/main/NavBarLink.tsx
Labels: size/m, DB Migration

#4138 test/load: Add K6 for load testing and example scripts
  .eslintrc.js
  Makefile
  devtools/gettool/getk6.go
  devtools/gettool/run.go
  k6.version
  package.json
  test/load/README.md
  test/load/hello.ts
  test/load/k6-run
  test/load/lib/entity.ts
  test/load/lib/graphql.ts
  test/load/lib/login.ts
  test/load/lib/rotation.ts
  test/load/update-random-rotations.ts
  yarn.lock
Labels: size/l

#4142 integrationkey/uik: refactor eval logic
  integrationkey/uik/compiledaction.go
  integrationkey/uik/compiledaction_test.go
  integrationkey/uik/compiledconfig.go
  integrationkey/uik/compiledconfig_test.go
  integrationkey/uik/compiledrule.go
  integrationkey/uik/compiledrule_test.go
  integrationkey/uik/compilerule.go
  integrationkey/uik/compilerule_test.go
  integrationkey/uik/handler.go
Labels: size/l

#4149 admin/apikeys: add CodeMirror editor for editing keys
  package.json
  test/integration/gqlapikeys.spec.ts
  web/src/app/admin/admin-api-keys/AdminAPIKeyCreateDialog.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyEditDialog.tsx
  web/src/app/admin/admin-api-keys/AdminAPIKeyForm.tsx
  web/src/app/editor/GraphQLEditor.tsx
  web/src/app/index.tsx
  web/src/app/theme/themeConfig.tsx
  web/src/app/theme/useTheme.ts
  yarn.lock
Labels: size/m

#4152 engine: update advisory lock handling and add locked transaction support
  engine/message/db.go
  engine/processinglock/conn.go
Labels: size/s

#4151 uik: Add code editor for Expr fields
  .eslintignore
  Makefile
  package.json
  test/integration/uik.spec.ts
  web/src/app/editor/ExprEditor.tsx
  web/src/app/editor/expr-lang.ts
  web/src/app/editor/expr-parser.ts
  web/src/app/editor/expr.grammar
  web/src/app/selection/DynamicActionForm.tsx
  web/src/app/services/UniversalKey/DefaultActionEditDialog.tsx
  web/src/app/services/UniversalKey/ExprField.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleDialog.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleForm.tsx
  yarn.lock
Labels: size/l

#4153 engine/processinglock: enable shared locking for concurrent work
  engine/processinglock/conn.go
  engine/processinglock/lock.go
  engine/processinglock/queries.sql
  engine/signalmgr/schedulemessages.go
  engine/signalmgr/setup.go
  gadb/queries.sql.go
Labels: size/s

#4141 test/load: Expands operations performed and use unique users for each VU
  Makefile
  package.json
  test/load/lib/entity.ts
  test/load/lib/graphql.ts
  test/load/lib/login.ts
  test/load/lib/rand.ts
  test/load/lib/rotation.ts
  test/load/lib/user.ts
  test/load/update-random-rotations.ts
  tsconfig.json
  yarn.lock
Labels: size/l

#4155 dev: update prometheus to v3
  prometheus.version
Labels: size/xs

#4154 graphql: enhance GraphQL schema documentation for mutations and queries
  graphql2/generated.go
  graphql2/graph/_Mutation.graphqls
  graphql2/graph/_Query.graphqls
  graphql2/models_gen.go
  graphql2/schema.graphql
Labels: size/l

#4167 http: fix Content Security Policy for riverui
  app/secureheaders.go
Labels: size/s
