Repository target/goalert, pull requests merged in 2024-02, with the labels that each got.

#3645 ci: upgrade node version
  .yarnrc.yml
  Makefile
  devtools/ci/dockerfiles/build-env/Dockerfile
  devtools/ci/tasks/scripts/codecheck.sh
  package.json
  yarn.lock
Labels: size/s

#3652 web: convert user contact method .js dependencies to .jsx
  web/src/app/dialogs/FormDialog.jsx
  web/src/app/dialogs/components/DialogContentError.jsx
  web/src/app/dialogs/components/DialogTitleWrapper.jsx
  web/src/app/forms/Form.jsx
  web/src/app/forms/FormContainer.jsx
  web/src/app/forms/FormField.jsx
  web/src/app/main/ErrorBoundary.jsx
  web/src/app/util/OtherActions.jsx
  web/src/app/util/OtherActionsDesktop.jsx
  web/src/app/util/OtherActionsMobile.jsx
Labels: size/xs

#3657 dev: rename components from .js to .jsx
  web/src/app/escalation-policies/PolicyStepForm.jsx
  web/src/app/escalation-policies/PolicyStepsCard.jsx
  web/src/app/icons/components/Icons.jsx
  web/src/app/schedules/ScheduleOverrideDialog.jsx
  web/src/app/schedules/ScheduleOverrideList.jsx
  web/src/app/schedules/ScheduleTZFilter.jsx
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeButton.jsx
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeForm.jsx
  web/src/app/schedules/calendar-subscribe/CalendarSuccessForm.jsx
  web/src/app/selection/QuerySelect.jsx
  web/src/app/services/ServiceLabelForm.jsx
  web/src/app/util/AppBarSearchContainer.jsx
  web/src/app/util/FilterContainer.jsx
  web/src/app/util/Markdown.jsx
  web/src/app/util/PageActions.jsx
  web/src/app/util/Search.jsx
  web/src/app/wizard/WizardForm.jsx
  web/src/app/wizard/WizardRouter.jsx
  web/src/app/wizard/WizardScheduleForm.jsx
Labels: size/xs

#3660 graphql: destinations: add user CM destination info resolver
  graphql2/generated.go
  graphql2/graph/_directives.graphqls
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/user.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  user/search.go
  web/src/app/storybook/defaultDestTypes.ts
  web/src/schema.d.ts
Labels: size/m

#3659 graphql: destinations: add `dest` as a field on OnCallNotificationRule
  graphql2/generated.go
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/destinationdisplayinfo.go
  graphql2/graphqlapp/schedule.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  web/src/schema.d.ts
Labels: size/m

#3656 destinations: update schedule notification list to use destinations
  web/src/app/lists/DraggableListItem.tsx
  web/src/app/lists/FlatList.tsx
  web/src/app/lists/FlatListItem.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.tsx
  web/src/app/schedules/on-call-notifications/util.ts
  web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
  web/src/app/util/DestinationAvatar.tsx
  web/src/app/util/DestinationChip.tsx
Labels: size/l

#3663 users: use generic destinations for user CM form
  package.json
  web/src/app/forms/FormField.jsx
  web/src/app/selection/DestinationField.stories.tsx
  web/src/app/selection/DestinationInputDirect.stories.tsx
  web/src/app/selection/DestinationInputDirect.tsx
  web/src/app/selection/DestinationSearchSelect.stories.tsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/users/UserContactMethodFormDest.stories.tsx
  web/src/app/users/UserContactMethodFormDest.tsx
  web/src/app/util/DestinationChip.stories.tsx
  web/src/app/util/DestinationInputChip.stories.tsx
  web/src/app/util/RequireConfig.tsx
  web/src/app/util/TelTextField.stories.tsx
  web/src/app/util/Time.stories.tsx
  yarn.lock
Labels: size/l

#3665 ep: destinations: update step list/actions to use dest-types
  graphql2/generated.go
  graphql2/graph/escalationpolicy.graphqls
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/escalationpolicy.go
  web/src/app/escalation-policies/PolicyStepsCard.jsx
  web/src/app/escalation-policies/PolicyStepsQuery.tsx
  web/src/app/escalation-policies/stepUtil.tsx
  web/src/app/util/DestinationAvatar.tsx
  web/src/schema.d.ts
Labels: size/m

#3677 github: labeler: enable fail_if_xl flag
  .github/workflows/labeler.yml
Labels: size/xs

#3676 dest: return proper data in graphql errors
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationvalidation.go
  notification/slack/channel.go
  notification/slack/user.go
  notification/slack/usergroup.go
Labels: size/l

#3678 storybook: add exp flags helper
  .storybook/preview.ts
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.stories.tsx
  web/src/app/selection/DestinationField.stories.tsx
  web/src/app/selection/DestinationInputDirect.stories.tsx
  web/src/app/selection/DestinationSearchSelect.stories.tsx
  web/src/app/storybook/graphql.ts
  web/src/app/users/UserContactMethodFormDest.stories.tsx
  web/src/app/util/DestinationChip.stories.tsx
  web/src/app/util/DestinationInputChip.stories.tsx
  web/src/app/util/TelTextField.stories.tsx
  web/src/app/util/useExpFlag.ts
Labels: size/s

#3679 dev: update Go to 1.22
  .github/workflows/codeql.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/main.yml
  devtools/ci/dockerfiles/build-env/Dockerfile
  devtools/ci/dockerfiles/goalert/Dockerfile
  devtools/ci/tasks/build-all.yml
  devtools/ci/tasks/build-binaries.yml
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/ci/tasks/test-smoketest.yml
  go.mod
Labels: size/s

#3682 go: fix toolchain error with go
  go.mod
Labels: size/xs

#3683 fix: alert detail markdown link bug
  web/src/app/util/safeURL.test.ts
  web/src/app/util/safeURL.ts
Labels: size/s

#3687 dev: Update tool versions
  .eslintignore
  gadb/db.go
  gadb/models.go
  gadb/queries.sql.go
  golangci-lint.version
  pkg/sysapi/sysapi.pb.go
  pkg/sysapi/sysapi_grpc.pb.go
  prometheus.version
  protoc.version
  sqlc.version
  swo/swodb/db.go
  swo/swodb/models.go
  swo/swodb/queries.sql.go
Labels: size/xs

#3684 users: use generic destinations for user contact method list component
  graphql2/graphqlapp/contactmethod.go
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/users/UserContactMethodListDest.stories.tsx
  web/src/app/users/UserContactMethodListDest.tsx
  web/src/app/users/UserDetails.tsx
Labels: size/l

#3686 Pprof endpoint
  Procfile
  Procfile.prod
  app/cmd.go
  app/pprof.go
  web/src/app/localdev/LocalDev.tsx
Labels: size/s

#3698 dest api: Clean up error API
  graphql2/generated.go
  graphql2/graph/errorcodes.graphqls
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/destinationvalidation.go
  graphql2/models_gen.go
  web/src/app/selection/DestinationField.stories.tsx
  web/src/app/selection/DestinationField.tsx
  web/src/app/users/UserContactMethodFormDest.stories.tsx
  web/src/app/users/UserContactMethodFormDest.tsx
  web/src/app/util/errtypes.ts
  web/src/app/util/errutil.test.ts
  web/src/app/util/errutil.ts
  web/src/errors.d.ts
  web/src/schema.d.ts
Labels: size/l

#3664 users: use generic destinations for user CM create dialog component
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationvalidation.go
  package.json
  web/src/app/dialogs/FormDialog.jsx
  web/src/app/forms/FormField.jsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/users/UserContactMethodCreateDialogDest.stories.tsx
  web/src/app/users/UserContactMethodCreateDialogDest.tsx
  web/src/app/users/UserContactMethodFormDest.tsx
  web/src/app/users/UserContactMethodListDest.stories.tsx
  web/src/app/util/RequireConfig.tsx
  yarn.lock
Labels: size/l

#3702 dest/graphql: convert comments to description strings
  graphql2/graph/destinations.graphqls
  graphql2/graph/errorcodes.graphqls
  graphql2/models_gen.go
Labels: size/l

#3701 users: use generic destinations for User Notification Rule List component
  web/src/app/users/UserDetails.tsx
  web/src/app/users/UserNotificationRuleListDest.stories.tsx
  web/src/app/users/UserNotificationRuleListDest.tsx
Labels: size/l

#3700 dest: add API support to create EP step with destinations
  graphql2/generated.go
  graphql2/graph/escalationpolicy.graphqls
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/compat.go
  graphql2/graphqlapp/contactmethod.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  graphql2/graphqlapp/escalationpolicy.go
  graphql2/models_gen.go
  web/src/schema.d.ts
  yarn.lock
Labels: size/l

#3706 dev: fix PR merge conflict
  graphql2/graphqlapp/destinationtypes.go
Labels: size/s

#3704 dest: add sched notif form
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsFormDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsFormDest.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.stories.tsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/util/RequireConfig.tsx
Labels: size/l

#3715 dev: format graphql files with prettier
  graphql2/graph/_Mutation.graphqls
  graphql2/graph/_Query.graphqls
  graphql2/graph/escalationpolicy.graphqls
  graphql2/schema.graphql
  package.json
Labels: size/s

#3705 dest: sched notifications create dialog
  graphql2/generated.go
  graphql2/graphqlapp/destinationtypes.go
  graphql2/graphqlapp/destinationvalidation.go
  graphql2/graphqlapp/schedule.go
  graphql2/schema.graphql
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialogDest.stories.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialogDest.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsListDest.tsx
  web/src/app/schedules/useScheduleTZ.ts
  web/src/app/selection/DestinationField.tsx
  web/src/schema.d.ts
Labels: size/l

#3721 util/Markdown: fix handling of links with URL-escapable characters
  web/src/app/util/Markdown.stories.tsx
  web/src/app/util/safeURL.test.ts
  web/src/app/util/safeURL.ts
Labels: size/m
