Repository target/goalert, pull requests merged in 2024-01, with the labels that each got.

#3571 dev: Use Storybook for component testing
  .eslintrc.js
  .gitignore
  .storybook/main.ts
  .storybook/msw.ts
  .storybook/preview.ts
  .storybook/static/mockServiceWorker.js
  .yarnrc.yml
  Makefile
  package.json
  playwright-ct.config.ts
  playwright.config.ts
  playwright/index.html
  playwright/index.tsx
  playwright/playwright-ct.bin.js
  playwright/playwright-e2e.bin.js
  web/src/app/env.ts
  web/src/app/storybook/decorators.tsx
  web/src/app/storybook/graphql.ts
  web/src/app/theme/themeConfig.tsx
  web/src/app/users/UserContactMethodCreateDialog.tsx
  web/src/app/util/RequireConfig.tsx
  web/src/app/util/TelTextField.ct-spec.tsx
  web/src/app/util/TelTextField.stories.tsx
  web/src/app/util/TelTextField.story.tsx
  web/src/app/util/TelTextField.tsx
  web/src/app/util/Time.stories.tsx
  web/src/app/util/Time.tsx
  web/src/app/util/timeFormat.ts
  yarn.lock
Labels: size/xl

#3530 add label chips to service details
  web/src/app/details/DetailsPage.tsx
  web/src/app/services/ServiceDetails.tsx
Labels: size/s

#3579 dev: pipe storybook warnings to null
  .storybook/main.ts
  Makefile
Labels: size/xs

#3493 ui/urql: convert user dialogs to urql
  web/src/app/users/UserCreateDialog.tsx
  web/src/app/users/UserDeleteDialog.tsx
  web/src/app/users/UserEditDialog.tsx
  web/src/app/users/UserNotificationRuleCreateDialog.tsx
  web/src/app/users/UserNotificationRuleDeleteDialog.tsx
  web/src/app/users/UserNotificationRuleList.tsx
Labels: size/l

#3580 ui: update favicon
  web/index.html
  web/src/app/public/icons/favicon-128.png
  web/src/app/public/icons/favicon-16.png
  web/src/app/public/icons/favicon-192.png
  web/src/app/public/icons/favicon-32.png
  web/src/app/public/icons/favicon-64.png
  web/src/app/public/icons/favicon.ico
Labels: size/xs

#3582 ui: update Select gql imports to use urql
  web/src/app/selection/EscalationPolicySelect.tsx
  web/src/app/selection/IntegrationKeySelect.tsx
  web/src/app/selection/LabelKeySelect.tsx
  web/src/app/selection/LabelValueSelect.tsx
  web/src/app/selection/RotationSelect.js
  web/src/app/selection/ScheduleSelect.js
  web/src/app/selection/ServiceSelect.js
  web/src/app/selection/SlackChannelSelect.js
  web/src/app/selection/TimeZoneSelect.js
  web/src/app/selection/UserSelect.js
Labels: size/s

#3583 ui: update ServiceCreateDialog and ServiceLabelCreateDialog to use urql
  web/src/app/services/ServiceCreateDialog.tsx
  web/src/app/services/ServiceLabelCreateDialog.tsx
Labels: size/s

#3525 ui/schedules: convert ScheduleRuleList, ScheduleRuleCreateDialog, ScheduleRuleEditDialog to typescript
  web/src/app/schedules/ScheduleRuleCreateDialog.tsx
  web/src/app/schedules/ScheduleRuleEditDialog.tsx
  web/src/app/schedules/ScheduleRuleForm.tsx
  web/src/app/schedules/ScheduleRuleList.tsx
Labels: ts-conversion, size/m

#3588 ui: DestinationInputDirect component
  web/src/app/selection/DestinationInputDirect.stories.tsx
  web/src/app/selection/DestinationInputDirect.tsx
Labels: size/l

#3584 ui: update SetFavoriteButton and graphql.test.js to urql
  web/src/app/util/QuerySetFavoriteButton.tsx
  web/src/app/util/graphql.test.js
  web/src/app/util/toTitleCase.ts
  web/src/cypress/e2e/alerts.cy.ts
Labels: size/s

#3587 ui: update temp sched dialogs to use urql, add additionalTypenames
  web/src/app/schedules/temp-sched/TempSchedDeleteConfirmation.tsx
  web/src/app/schedules/temp-sched/TempSchedDialog.tsx
Labels: size/s

#3586 util: add DestinationChip and DestinationInputChip components
  web/src/app/util/DestinationChip.stories.tsx
  web/src/app/util/DestinationChip.tsx
  web/src/app/util/DestinationInputChip.stories.tsx
  web/src/app/util/DestinationInputChip.tsx
Labels: size/l

#3589 ui: update schedule oncall hooks and util to use urql
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsCreateDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsEditDialog.tsx
  web/src/app/schedules/on-call-notifications/ScheduleOnCallNotificationsList.tsx
  web/src/app/schedules/on-call-notifications/hooks.ts
  web/src/app/schedules/on-call-notifications/util.ts
Labels: size/s

#3585 ui: update WizardRouter to use urql
  web/src/app/wizard/WizardRouter.js
Labels: size/m

#3593 ui: DestinationSearchSelect component
  graphql2/generated.go
  graphql2/graph/destinations.graphqls
  graphql2/graphqlapp/destinationtypes.go
  graphql2/models_gen.go
  web/src/app/selection/DestinationSearchSelect.stories.tsx
  web/src/app/selection/DestinationSearchSelect.tsx
  web/src/app/selection/MaterialSelect.tsx
  web/src/schema.d.ts
Labels: size/xl

#3531 config: add Service.RequiredLabels
  config/config.go
  graphql2/mapconfig.go
  web/src/app/services/ServiceCreateDialog.tsx
  web/src/app/services/ServiceEditDialog.tsx
  web/src/app/services/ServiceForm.tsx
  web/src/schema.d.ts
Labels: size/m

#3604 config: Add option to auto-close acked alerts
  config/config.go
  engine/cleanupmanager/db.go
  engine/cleanupmanager/update.go
  graphql2/mapconfig.go
  web/src/schema.d.ts
Labels: size/s

#3609 users: add assertion for editing contact method
  test/integration/email-cm.spec.ts
Labels: size/s

#3606 ui/temp-sched: Add fixed shifts for temporary schedules
  web/src/app/schedules/temp-sched/TempSchedAddNewShift.tsx
  web/src/app/schedules/temp-sched/TempSchedDialog.tsx
  web/src/app/schedules/temp-sched/TempSchedShiftsList.tsx
  web/src/app/schedules/temp-sched/sharedUtils.tsx
  web/src/app/schedules/temp-sched/shiftsListUtil.test.ts
  web/src/app/schedules/temp-sched/shiftsListUtil.tsx
  web/src/app/util/luxon-helpers.test.ts
  web/src/app/util/luxon-helpers.ts
  web/src/app/util/timeFormat.ts
  web/src/cypress/e2e/temporarySchedule.cy.ts
Labels: size/xl

#3592 selection: add DestinationField component and tests
  web/src/app/selection/DestinationField.stories.tsx
  web/src/app/selection/DestinationField.tsx
  web/src/app/selection/DestinationInputDirect.tsx
  web/src/app/storybook/defaultDestTypes.ts
  web/src/app/storybook/graphql.ts
  web/src/app/util/RequireConfig.tsx
Labels: size/l

#3603 prometheus: add service_id to created alerts and sent notification counters
  alert/metrics.go
  alert/store.go
  engine/sendmessage.go
  notification/alertstatus.go
  notification/manager.go
  notification/metrics.go
Labels: size/s

#3590 ui: convert CalendarSubscribe dialogs to ts and to use urql instead of apollo
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeCreateDialog.tsx
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeDeleteDialog.js
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeDeleteDialog.tsx
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeEditDialog.tsx
  web/src/app/users/UserCalendarSubscriptionList.tsx
Labels: size/m

#3559 heartbeats: Add support for specifying additional details
  engine/heartbeatmanager/db.go
  engine/heartbeatmanager/process.go
  gadb/models.go
  graphql2/generated.go
  graphql2/graphqlapp/heartbeatmonitor.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  heartbeat/monitor.go
  heartbeat/store.go
  migrate/migrations/20240125091537-hb-addl-details.sql
  migrate/schema.sql
  web/src/app/forms/FormField.js
  web/src/app/services/HeartbeatMonitorCreateDialog.tsx
  web/src/app/services/HeartbeatMonitorEditDialog.tsx
  web/src/app/services/HeartbeatMonitorForm.tsx
  web/src/schema.d.ts
Labels: size/m

#3625 ui/urql: update schedule queries and mutations
  test/integration/schedules.spec.ts
  web/src/app/schedules/ScheduleCreateDialog.tsx
  web/src/app/schedules/ScheduleDeleteDialog.tsx
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/ScheduleOverrideCreateDialog.tsx
  web/src/app/schedules/ScheduleOverrideDialog.js
  web/src/app/schedules/ScheduleOverrideList.js
  web/src/app/schedules/ScheduleShiftList.tsx
Labels: size/m

#3626 cli: check for scheme on public-url
  app/cmd.go
Labels: size/xs

#3627 cli: normalize public url
  app/cmd.go
Labels: size/xs

#3629 dev/admin: prod build validation
  .gitignore
  Makefile
  Makefile.binaries.mk
  Procfile.integration
  Procfile.prod
  devtools/genmake/template.mk
  web/handler.go
  web/src/esbuild.config.js
Labels: size/s

#3640 dev: add GOALERT_VERSION to cy commands
  Makefile
Labels: size/xs
