Repository target/goalert, pull requests merged in 2025-02, with the labels that each got.

#4264 ci: update permissions for Dependabot auto-approve workflow
  .github/workflows/dep-autoapprove.yml
Labels: size/xs

#4260 feat: fix rotation advance when removing a user
  web/src/app/rotations/RotationUserDeleteDialog.tsx
Labels: size/xs

#4262 engine: update rate limit rules for on-call user notifications
  engine/message/ratelimit.go
Labels: size/xs

#4261 fix(lifecycle): skip shutdown wait on run failure
  app/lifecycle/manager.go
Labels: size/xs

#4259 service: fix label error messaging for create and edit
  web/src/app/services/ServiceCreateDialog.tsx
  web/src/app/services/ServiceEditDialog.tsx
  web/src/app/services/ServiceForm.tsx
  web/src/app/util/ErrorConsumer.ts
Labels: size/m

#4257 fix(notice): handle negative limit in FindAllServiceNotices
  notice/store.go
Labels: size/xs

#4255 feat: add Twilio configuration check in AdminToolbox component
  web/src/app/admin/AdminToolbox.tsx
Labels: size/xs

#4243 http: Add method restrictions to routes, fix response codes
  app/inithttp.go
  calsub/http.go
  genericapi/handler.go
Labels: size/s

#4242 schedules: add support for linking directly to creating a new schedule override
  web/src/app/schedules/ScheduleDetails.tsx
  web/src/app/schedules/ScheduleOverrideDialog.jsx
Labels: size/xs

#4282 Converted all remaining selection .js to typescript
  web/src/app/selection/RotationSelect.ts
  web/src/app/selection/ScheduleSelect.ts
  web/src/app/selection/ServiceSelect.js
  web/src/app/selection/SlackChannelSelect.ts
  web/src/app/selection/TimeZoneSelect.ts
  web/src/app/selection/UserSelect.ts
  web/src/app/selection/index.ts
Labels: size/xs

#4083 build: yarn to bun
  .github/workflows/main.yml
  .storybook/main.ts
  .yarn/releases/yarn-4.5.3.cjs
  .yarnrc.yml
  Makefile
  Makefile.binaries.mk
  Procfile
  Procfile.cypress
  Procfile.cypress.ci
  Procfile.cypress.prod
  Procfile.swo
  bun.lock
  bun.version
  devtools/ci/tasks/scripts/codecheck.sh
  devtools/genmake/template.mk
  devtools/gettool/getbun.go
  devtools/gettool/run.go
  devtools/scripts/arch-check.sh
  package.json
  tsconfig.json
  web/src/genschema.go
  yarn.lock
Labels: size/m
