Repository target/goalert, pull requests merged in 2025-03, with the labels that each got.

#4292 rotations: fix v1 -> v2 migration logic
  engine/rotationmanager/advance.go
  engine/rotationmanager/update.go
Labels: size/s

#4293 graphql: add `alertStats` field on `Service`
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graph/service.graphqls
  graphql2/graphqlapp/messagelog.go
  graphql2/graphqlapp/queries.sql
  graphql2/graphqlapp/service.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  migrate/migrations/20250306140905-polyfill-date-bin.sql
  migrate/schema.sql
  util/timeutil/isoduration.go
  web/src/schema.d.ts
Labels: size/m, DB Migration

#4298 feat: vscode: add launch configuration for debugging
  .gitignore
  .vscode/launch.json
  Procfile.tools
Labels: size/s

#4297 deps: update eslint to latest
  .eslintignore
  .eslintrc.js
  bun.lock
  cypress.config.js
  eslint.config.mjs
  package.json
  prettier.config.js
  web/src/app/env.ts
  web/src/app/util/debug.ts
  web/src/cypress/support/graphql.ts
  web/src/global.d.ts
Labels: size/m

#4299 sqlutil: fix deadlock in NOTIFY listener (refactor)
  app/listenevents.go
  app/runapp.go
  app/startup.go
  go.mod
  go.sum
  test/smoke/harness/harness.go
  util/log/log.go
  util/sqlutil/listener.go
Labels: size/l

#4300 Jsx to tsx convert calendar subscribe jsx files
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeButton.tsx
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeCreateDialog.tsx
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeEditDialog.tsx
  web/src/app/schedules/calendar-subscribe/CalendarSubscribeForm.tsx
  web/src/app/schedules/calendar-subscribe/CalendarSuccessForm.tsx
Labels: size/s

#4278 ui/icons: convert icon components to typescript
  web/src/app/icons/components/Icons.tsx
  web/src/app/icons/index.ts
  web/src/app/services/ServiceOnCallList.tsx
Labels: size/s

#4269 engine: refactor rotations to process through job queue
  app/initgraphql.go
  engine/engine.go
  engine/rotationmanager/advance.go
  engine/rotationmanager/db.go
  engine/rotationmanager/lookforwork.go
  engine/rotationmanager/queries.sql
  engine/rotationmanager/setup.go
  engine/rotationmanager/update.go
  engine/rotationmanager/updaterotation.go
  gadb/models.go
  gadb/queries.sql.go
  graphql2/graphqlapp/app.go
  graphql2/graphqlapp/rotation.go
  migrate/migrations/20250311113136-track-rotation-updates.sql
  migrate/schema.sql
  schedule/rotation/update.go
  test/smoke/harness/harness.go
  test/smoke/migrations_test.go
Labels: size/l, DB Migration

#4279 ui/service: convert ServiceLabelForm to typescript
  web/src/app/forms/FormField.jsx
  web/src/app/services/ServiceLabelEditDialog.tsx
  web/src/app/services/ServiceLabelForm.tsx
Labels: size/s

#4283 ui/util: convert js files to typescript
  web/src/app/util/LuxonLocalizer.js
  web/src/app/util/LuxonLocalizer.ts
  web/src/app/util/MountWatcher.js
  web/src/app/util/graphql.test.ts
  web/src/app/util/graphql.ts
  web/src/app/util/promiseBatch.ts
  web/src/app/util/query_param.js
  web/src/app/util/query_param.ts
  web/src/app/util/shrinkWorkaround.ts
Labels: size/l

#4306 schedules: Fixes a bug where 'replace' overrides would behave as an 'add' + 'delete' rather than replace
  engine/schedulemanager/update.go
  test/smoke/harness/harness.go
  test/smoke/scheduleoverrideadd_test.go
  test/smoke/scheduleoverrideremove_test.go
  test/smoke/scheduleoverridereplace_test.go
Labels: size/l

#4304 ui/dev: Introduce CompList to replace FlatList
  web/src/app/lists/CompList.tsx
  web/src/app/lists/CompListItems.tsx
  web/src/app/services/ServiceLabelList.tsx
  web/src/app/services/ServiceList.tsx
  web/src/app/services/ServiceOnCallList.tsx
Labels: size/l

#4305 ui/dev: Add ReorderGroup and ReorderableItem for CompList
  web/src/app/escalation-policies/PolicyStepsCard.tsx
  web/src/app/lists/CompList.tsx
  web/src/app/lists/CompListItems.tsx
  web/src/app/lists/ReorderGroup.tsx
  web/src/app/lists/ReorderableItem.tsx
Labels: size/l

#4320 fix: Exclude disabled subscriptions from inactivity queries
  engine/cleanupmanager/queries.sql
  gadb/queries.sql.go
Labels: size/xs

#4315 notification/twilio: add base RCS support
  config/config.go
  devtools/mocktwilio/server.go
  devtools/mocktwilio/sms.go
  engine/message/db.go
  engine/message/status.go
  gadb/models.go
  graphql2/graphqlapp/alert.go
  graphql2/mapconfig.go
  migrate/migrations/20250318133045-om-status-read.sql
  migrate/migrations/20250318133231-inc-msg-module.sql
  migrate/schema.sql
  notification/compat.go
  notification/nfymsg/state.go
  notification/store.go
  notification/twilio/message.go
  notification/twilio/sms.go
  test/smoke/harness/graphql.go
  test/smoke/harness/harness.go
  test/smoke/harness/mailpit.go
  test/smoke/harness/matchers.go
  test/smoke/twiliosmsack_test.go
  test/smoke/twiliosmsackrcs_test.go
  web/src/schema.d.ts
Labels: size/l, DB Migration

#4313 ui/services: migrate service components from FlatList to CompList
  web/src/app/lists/CompList.tsx
  web/src/app/services/HeartbeatMonitorList.tsx
  web/src/app/services/IntegrationKeyList.tsx
  web/src/app/services/UniversalKey/UniversalKeyDefaultActions.tsx
  web/src/app/services/UniversalKey/UniversalKeyRuleConfig.tsx
Labels: size/m

#4307 Sqlc alert store
  alert/alertlog/queries.sql
  alert/alertlog/store.go
  alert/metadata.go
  alert/queries.sql
  alert/store.go
  gadb/queries.sql.go
Labels: size/m

#4324 messages: record and display full message status history for notificaitons
  alert/alertlog/entry.go
  gadb/models.go
  gadb/queries.sql.go
  graphql2/generated.go
  graphql2/graph/alerts.graphqls
  graphql2/graphqlapp/alert.go
  graphql2/graphqlapp/queries.sql
  graphql2/graphqlapp/query.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  migrate/migrations/20250327120521-om-history.sql
  migrate/schema.sql
  web/src/app/alerts/AlertDetailLogs.tsx
  web/src/schema.d.ts
Labels: size/l, DB Migration
