Repository target/goalert, pull requests merged in 2025-07, with the labels that each got.

#4384 Feat: ServiceSearch "only"
  graphql2/generated.go
  graphql2/graphqlapp/service.go
  graphql2/models_gen.go
  graphql2/schema.graphql
  service/search.go
  service/service_test.go
  test/smoke/graphqlservicesearchonly_test.go
  web/src/schema.d.ts
Labels: size/l

#4385 fix: increase timeout in TestIDLocker_CancelQueue for better stability
  ctxlock/idlocker_test.go
Labels: size/xs

#4392 uik: add direct links for externally created uik with warning
  web/src/app/services/IntegrationKeyList.tsx
  web/src/app/services/UniversalKey/UniversalKeyPage.tsx
Labels: size/s

#4391 engine/schedulemanager: refactor schedule calculation for maintainability and job queue migration
  Makefile
  dataloader/fetcher_test.go
  engine/schedulemanager/calcupdates.go
  engine/schedulemanager/calcupdates_test.go
  engine/schedulemanager/update.go
  go.mod
  go.sum
  test/smoke/harness/email.go
  test/smoke/harness/harness.go
  test/smoke/harness/mailpit.go
  test/smoke/harness/mailpit_test.go
  test/smoke/harness/slack.go
Labels: size/l
